### ISSUE TITLE
Randomly failing to get the watermark offsets

### ISSUE THREAD

**Issue by qiuwei** [confluentinc/confluent-kafka-python#1043]
Description
===========
I am using Confluent kafka version ('1.6.0', 17170432), librdkafka version: ('1.6.0', 17170687) on Ubuntu Linux 20.04 and macOS BigSur 11.2.1. Kafka broker version is 2.5.1.

client configuration is as follows:
```
{
            "bootstrap.servers": bootstrap_servers,
            "group.id": uuid.uuid1(),
            "session.timeout.ms": 6000,
            "default.topic.config": {
                "auto.offset.reset": "latest",
                "enable.auto.commit": False,
            },
            'debug': 'topic,metadata,protocol,cgrp'


}
```

How to reproduce
================
The following code to get the watermarks fails randomly. Most of the time, it returns the correct result, but sometimes it throws Exception `cimpl.KafkaException: KafkaError{code=_UNKNOWN_PARTITION,val=-190,str="Failed to get watermark offsets: Local: Unknown partition"}`.

```
consumer = confluent_kafka.Consumer(**kafka_conf)
tp = TopicPartition(topic, 0)
low, high = consumer.get_watermark_offsets(tp)
```

I suspect that I am doing something wrong.

Log:
```
Testing started at 7:07 AM ...
/usr/local/Caskroom/miniconda/base/envs/insight-kafka-reader-zFPeAhwj-py3.7/bin/python "/Users/wqiu/Library/Application Support/JetBrains/IntelliJIdea2020.1/plugins/python/helpers/pycharm/_jb_unittest_runner.py" --target test_insight_kafka_client.TestInsightKafkaClient.test_read_latest_kafka_msgs
Launching unittests with arguments python -m unittest test_insight_kafka_client.TestInsightKafkaClient.test_read_latest_kafka_msgs in /Users/wqiu/Projects/insight_kafka_reader/tests

%7|1614553677.591|MEMBERID|rdkafka#consumer-1| [thrd:app]: Group "cbbab1ba-7a19-11eb-8bf3-acde48001122": updating member id "(not-set)" -> ""
%7|1614553677.591|CGRPSTATE|rdkafka#consumer-1| [thrd:main]: Group "cbbab1ba-7a19-11eb-8bf3-acde48001122" changed state init -> query-coord (join-state init)
%7|1614553677.591|INIT|rdkafka#consumer-1| [thrd:app]: librdkafka v1.6.0 (0x10600ff) rdkafka#consumer-1 initialized (builtin.features gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,zstd,sasl_oauthbearer, STRIP STATIC_LINKING CC GXX PKGCONFIG OSXLD LIBDL PLUGINS ZLIB SSL SASL_CYRUS ZSTD HDRHISTOGRAM SNAPPY SOCKEM SASL_SCRAM SASL_OAUTHBEARER CRC32C_HW, debug 0x18c)
%7|1614553677.591|CGRPQUERY|rdkafka#consumer-1| [thrd:main]: Group "cbbab1ba-7a19-11eb-8bf3-acde48001122": no broker available for coordinator query: intervaled in state query-coord
%7|1614553677.591|METADATA|rdkafka#consumer-1| [thrd:app]: Hinted cache of 1/1 topic(s) being queried
%7|1614553677.591|METADATA|rdkafka#consumer-1| [thrd:app]: Skipping metadata refresh of 1 topic(s): query partition leaders: no usable brokers
%7|1614553677.619|CONNECTED|rdkafka#consumer-1| [thrd:192.168.192.132:9093/bootstrap]: 192.168.192.132:9093/bootstrap: Connected (#1)
%7|1614553677.619|FEATURE|rdkafka#consumer-1| [thrd:192.168.192.132:9093/bootstrap]: 192.168.192.132:9093/bootstrap: Updated enabled protocol features +ApiVersion to ApiVersion
%7|1614553677.619|SEND|rdkafka#consumer-1| [thrd:192.168.192.132:9093/bootstrap]: 192.168.192.132:9093/bootstrap: Sent ApiVersionRequest (v3, 66 bytes @ 0, CorrId 1)
%7|1614553677.641|RECV|rdkafka#consumer-1| [thrd:192.168.192.132:9093/bootstrap]: 192.168.192.132:9093/bootstrap: Received ApiVersionResponse (v3, 358 bytes, CorrId 1, rtt 22.79ms)
%7|1614553677.642|METADATA|rdkafka#consumer-1| [thrd:192.168.192.132:9093/bootstrap]: Hinted cache of 1/1 topic(s) being queried
%7|1614553677.642|METADATA|rdkafka#consumer-1| [thrd:192.168.192.132:9093/bootstrap]: Requesting metadata for 1/1 topics: connected
%7|1614553677.642|METADATA|rdkafka#consumer-1| [thrd:192.168.192.132:9093/bootstrap]: 192.168.192.132:9093/bootstrap: Request metadata for 1 topic(s): connected
%7|1614553677.642|CGRPQUERY|rdkafka#consumer-1| [thrd:main]: 192.168.192.132:9093/bootstrap: Group "cbbab1ba-7a19-11eb-8bf3-acde48001122": querying for coordinator: intervaled in state query-coord
%7|1614553677.642|CGRPSTATE|rdkafka#consumer-1| [thrd:main]: Group "cbbab1ba-7a19-11eb-8bf3-acde48001122" changed state query-coord -> wait-coord (join-state init)
%7|1614553677.642|SEND|rdkafka#consumer-1| [thrd:192.168.192.132:9093/bootstrap]: 192.168.192.132:9093/bootstrap: Sent MetadataRequest (v4, 51 bytes @ 0, CorrId 2)
%7|1614553677.642|SEND|rdkafka#consumer-1| [thrd:192.168.192.132:9093/bootstrap]: 192.168.192.132:9093/bootstrap: Sent FindCoordinatorRequest (v2, 60 bytes @ 0, CorrId 3)
%7|1614553677.660|RECV|rdkafka#consumer-1| [thrd:192.168.192.132:9093/bootstrap]: 192.168.192.132:9093/bootstrap: Received MetadataResponse (v4, 125 bytes, CorrId 2, rtt 18.05ms)
%7|1614553677.660|METADATA|rdkafka#consumer-1| [thrd:main]: 192.168.192.132:9093/bootstrap: ===== Received metadata (for 1 requested topics): connected =====
%7|1614553677.660|METADATA|rdkafka#consumer-1| [thrd:main]: 192.168.192.132:9093/bootstrap: ClusterId: abbK1bwGQgS2_i7Drd4c5Q, ControllerId: 1
%7|1614553677.660|METADATA|rdkafka#consumer-1| [thrd:main]: 192.168.192.132:9093/bootstrap: 1 brokers, 1 topics
%7|1614553677.660|METADATA|rdkafka#consumer-1| [thrd:main]: 192.168.192.132:9093/bootstrap:   Broker #0/1: 192.168.192.132:9093 NodeId 1
%7|1614553677.660|METADATA|rdkafka#consumer-1| [thrd:main]: 192.168.192.132:9093/bootstrap:   Topic #0/1: MD_KLINE_1MIN_StockType with 1 partitions
%7|1614553677.660|METADATA|rdkafka#consumer-1| [thrd:main]: 192.168.192.132:9093/bootstrap: 1/1 requested topic(s) seen in metadata
%7|1614553677.660|LEADER|rdkafka#consumer-1| [thrd:192.168.192.132:9093/bootstrap]: 192.168.192.132:9093/1: Mapped 0 partition(s) to broker
%7|1614553677.665|DESTROY|rdkafka#consumer-1| [thrd:app]: Terminating instance (destroy flags NoConsumerClose (0x8))
%7|1614553677.665|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "cbbab1ba-7a19-11eb-8bf3-acde48001122" received op TERMINATE in state wait-coord (join-state init)
%7|1614553677.665|CGRPTERM|rdkafka#consumer-1| [thrd:main]: Terminating group "cbbab1ba-7a19-11eb-8bf3-acde48001122" in state wait-coord with 0 partition(s)
%7|1614553677.665|CLEARASSIGN|rdkafka#consumer-1| [thrd:main]: No current assignment to clear
%7|1614553677.665|DUMP|rdkafka#consumer-1| [thrd:main]: Assignment dump (started_cnt=0, wait_stop_cnt=0)
%7|1614553677.665|DUMP_ALL|rdkafka#consumer-1| [thrd:main]: List with 0 partition(s):
%7|1614553677.665|DUMP_PND|rdkafka#consumer-1| [thrd:main]: List with 0 partition(s):
%7|1614553677.665|DUMP_QRY|rdkafka#consumer-1| [thrd:main]: List with 0 partition(s):
%7|1614553677.665|DUMP_REM|rdkafka#consumer-1| [thrd:main]: List with 0 partition(s):
%7|1614553677.665|ASSIGNDONE|rdkafka#consumer-1| [thrd:main]: Group "cbbab1ba-7a19-11eb-8bf3-acde48001122": assignment operations done in join-state init (rebalance rejoin=false)
%7|1614553677.665|CGRPSTATE|rdkafka#consumer-1| [thrd:main]: Group "cbbab1ba-7a19-11eb-8bf3-acde48001122" changed state wait-coord -> term (join-state init)
%7|1614553677.665|ASSIGNMENT|rdkafka#consumer-1| [thrd:main]: Group "cbbab1ba-7a19-11eb-8bf3-acde48001122": clearing group assignment
%7|1614553677.665|DESTROY|rdkafka#consumer-1| [thrd:main]: Destroy internal
%7|1614553677.665|DESTROY|rdkafka#consumer-1| [thrd:main]: Removing all topics
%7|1614553677.665|BRKTERM|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: terminating: broker still has 2 refcnt(s), 0 buffer(s), 0 partition(s)
%7|1614553677.665|BRKTERM|rdkafka#consumer-1| [thrd::0/internal]: :0/internal: terminating: broker still has 2 refcnt(s), 0 buffer(s), 0 partition(s)
%7|1614553677.665|CGRPCOORD|rdkafka#consumer-1| [thrd:192.168.192.132:9093/bootstrap]: 192.168.192.132:9093/1: Group "cbbab1ba-7a19-11eb-8bf3-acde48001122" FindCoordinator response error: _DESTROY: Local: Broker handle destroyed
%7|1614553677.665|BRKTERM|rdkafka#consumer-1| [thrd:192.168.192.132:9093/bootstrap]: 192.168.192.132:9093/1: terminating: broker still has 2 refcnt(s), 0 buffer(s), 0 partition(s)
%7|1614553677.665|MEMBERID|rdkafka#consumer-1| [thrd:app]: Group "cbbab1ba-7a19-11eb-8bf3-acde48001122": updating member id "" -> "(not-set)"


Ran 1 test in 0.096s

FAILED (errors=1)

Error
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/unittest/case.py", line 628, in run
    testMethod()
  File "/Users/wqiu/Projects/insight_kafka_reader/tests/test_insight_kafka_client.py", line 11, in test_read_latest_kafka_msgs
    result = client.read_latest_kafka_msgs(topic,  kline1min2list, get_kline1min_header(), 100)
  File "/Users/wqiu/Projects/insight_kafka_reader/insight_kafka_reader/insight_kafka_client.py", line 201, in read_latest_kafka_msgs
    low, high = consumer.get_watermark_offsets(tp)
cimpl.KafkaException: KafkaError{code=_UNKNOWN_PARTITION,val=-190,str="Failed to get watermark offsets: Local: Unknown partition"}


Assertion failed

Process finished with exit code 1

Assertion failed

Assertion failed

```
Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [x] Apache Kafka broker version:
 - [x] Client configuration: `{...}`
 - [x] Operating system:
 - [x] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Thanks for reporting this issue.
I've reproduced and created a fix here: 
https://github.com/edenhill/librdkafka/pull/3287

**Comment by qiuwei** [comment]
Cool! thanks for the fix, will test it out.
