### ISSUE TITLE
Error getting request for apiKey: FIND_COORDINATOR, apiVersion: 0

### ISSUE THREAD

**Issue by ishadevops** [confluentinc/confluent-kafka-python#1180]
Description
===========
Confluent kafka version - confluentinc/cp-kafka:5.2.1
Single node broker 

Suddenly Kafka broker is throwing the below error, Could you please help 

Stack Trace

[2021-08-08 13:46:17,362] ERROR Closing socket for <private-ip>:9093-<ip>:47656-3726 because of error (kafka.network.Processor)
org.apache.kafka.common.errors.InvalidRequestException: Error getting request for apiKey: FIND_COORDINATOR, apiVersion: 0, connectionId: <private-ip>:9093-<ip>:47656-3726, listenerName: ListenerName(EXTERNAL), principal: User:ANONYMOUS
Caused by: org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'group_id': String length -1 cannot be negative
        at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:77)
        at org.apache.kafka.common.protocol.ApiKeys.parseRequest(ApiKeys.java:294)
        at org.apache.kafka.common.requests.RequestContext.parseRequest(RequestContext.java:63)
        at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:89)
        at kafka.network.Processor$$anonfun$processCompletedReceives$1.apply(SocketServer.scala:856)
        at kafka.network.Processor$$anonfun$processCompletedReceives$1.apply(SocketServer.scala:840)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at kafka.network.Processor.processCompletedReceives(SocketServer.scala:840)
        at kafka.network.Processor.run(SocketServer.scala:731)
        at java.lang.Thread.run(Thread.java:748)

 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
What's the confluent-kafka-python version and what's your client config?

**Comment by ishadevops** [comment]
Hi Edenhill,
Client config is confluent-kafka==1.2.0

**Comment by edenhill** [comment]
Please upgrade to the latest version (1.7.0) and try to reproduce
