### ISSUE TITLE
Kafka Connect is unable to deserialise Protobuf messages registered with schema registry

### ISSUE THREAD

**Issue by boofhead** [confluentinc/confluent-kafka-python#1213]
Description
===========
This seems like the same issue as experienced with the dotnet client here https://github.com/confluentinc/confluent-kafka-dotnet/issues/1542

Messages can be serialised and streamed to kafka using `SerializingProducer` and schema_registry. Serialization is valid (i.e. messages can be read and deserialised with `DeserializingConsumer`) however this does not use the schema registered with schema registry.  Using Kafka Connect with schema registry fails with:
```

Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Protobuf message for id 1

Caused by: java.lang.IllegalArgumentException: Illegal Capacity: -1

	at java.base/java.util.ArrayList.<init>(ArrayList.java:158)

	at io.confluent.kafka.schemaregistry.protobuf.MessageIndexes.readFrom(MessageIndexes.java:73)

	at io.confluent.kafka.serializers.protobuf.AbstractKafkaProtobufDeserializer.deserialize(AbstractKafkaProtobufDeserializer.java:121)

	at io.confluent.kafka.serializers.protobuf.AbstractKafkaProtobufDeserializer.deserializeWithSchemaAndVersion(AbstractKafkaProtobufDeserializer.java:242)

	at io.confluent.connect.protobuf.ProtobufConverter$Deserializer.deserialize(ProtobufConverter.java:174)

	at io.confluent.connect.protobuf.ProtobufConverter.toConnectData(ProtobufConverter.java:113)

	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)

	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertKey(WorkerSinkTask.java:530)

	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$1(WorkerSinkTask.java:493)

	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)

	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)

	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:132)

	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:493)

	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:473)

	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:328)

	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)

	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)

	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:182)

	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:231)

	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

	at java.base/java.lang.Thread.run(Thread.java:829)
```

How to reproduce
================
Run kafka-connect with any sink connector against topics containing Protobuf messages serialised with `SerializingProducer` and options to deserialise using schema registry:
```
      CONNECT_KEY_CONVERTER: io.confluent.connect.protobuf.ProtobufConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER: io.confluent.connect.protobuf.ProtobufConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
```

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 1.7.0
 - [ ] Apache Kafka broker version: 6.2.0
 - [ ] Client configuration: `{...}`
 - [ ] Operating system: linux64
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by cemeyer2** [comment]
https://github.com/confluentinc/confluent-kafka-python/issues/926

**Comment by jliunyu** [comment]
This one is fixed in v1.8.2, please update to the latest version.
