### ISSUE TITLE
Cannot establish OAUTH connection using SASL_PLAINTEXT

### ISSUE THREAD

**Issue by sidyag** [confluentinc/confluent-kafka-python#1358]
Description
===========

Receiving "SASL authentication error: SaslAuthenticate request received after successful authentication" continuously after successfully authenticating OAUTH token on server side.

Have attached the clientside code below, and serverside logs.

Somehow the client is constantly calling SASL_AUTHENTICATE repeatedly even after establishing the connection.

Could you advise how to overcome this?

How to reproduce
================

```
from confluent_kafka import Producer
import socket
import time
import json
import base64
import traceback

def oauth_cb(oauth_config):
    global seen_oauth_cb
    seen_oauth_cb = True
    print(oauth_config)
    #oauth_token=get_oauth_token()
    file=open('/home/ssm-user/bearer_producers/bearer_token.txt', 'r')
    oauth_token=file.readline()
    file.close()
    print("Token: ",oauth_token)
    oauth_token_bytes=oauth_token.encode('ascii')
    oauth_token_base64_bytes=base64.b64encode(oauth_token_bytes)
    oauth_token_base64=oauth_token_base64_bytes.decode('ascii')
    print("Encoded Token: ",oauth_token_base64)
    oauth_token_base64=oauth_token_base64.strip('=')
    print('Stripped Token: ',oauth_token_base64)

    return oauth_token_base64, time.time() + 300.0

def produce():
    conf = {'bootstrap.servers': "b-1.oauth-test-2.1d8hga.c1.kafka.us-east-1.amazonaws.com:12531",
        'client.id': socket.gethostname(),
        'security.protocol': 'SASL_PLAINTEXT',
        'sasl.mechanisms': 'OAUTHBEARER',
        'sasl.oauthbearer.config': 'testing',
        'oauth_cb': oauth_cb,
        'socket.timeout.ms': '100',
        'session.timeout.ms': 1000,  # Avoid close() blocking too long
    }

    producer = Producer(conf)
    topic="test_topic"
    try:
        producer.poll(0.0)
        print("Polled. Waiting.")
        time.sleep(2)
        producer.produce(topic, value="value_bearer_yay")
        print("Produced. Waiting.")
        time.sleep(2)
        producer.flush()
    except Exception:
        print(traceback.format_exc())
    print("Produced everything!")

def main():
    print("Starting producers!")
    produce()

if __name__ == "__main__":
    main()
```

Checklist
=========
Please provide the following information:

 - Versions: [ ('1.8.2', 17302016) and ('1.8.2', 17302271)]
 - [2.7.1 ] Apache Kafka broker version:
 
Client Logs:

```
%3|1654014544.938|FAIL|ip-10-0-0-103.ec2.internal#producer-1| [thrd:sasl_plaintext://b-1.oauth-test-2.1d8hga.c1.kafka.us-east-1.yag]: sasl_plaintext://b-1.oauth-test-2.1d8hga.c1.kafka.us-east-1.yagnik.people.aws.dev:12531/bootstrap: SASL authentication error: SaslAuthenticate request received after successful authentication (after 88ms in state AUTH_REQ)
%3|1654014545.143|FAIL|ip-10-0-0-103.ec2.internal#producer-1| [thrd:sasl_plaintext://b-1.oauth-test-2.1d8hga.c1.kafka.us-east-1.yag]: sasl_plaintext://b-1.oauth-test-2.1d8hga.c1.kafka.us-east-1.yagnik.people.aws.dev:12531/bootstrap: SASL authentication error: SaslAuthenticate request received after successful authentication (after 16ms in state AUTH_REQ, 1 identical error(s) suppressed)
```

Server logs:

```
[2022-05-31 16:40:18,246] DEBUG Set SASL server state to HANDSHAKE_REQUEST during authentication (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
[2022-05-31 16:40:18,247] DEBUG Handling Kafka request SASL_HANDSHAKE during authentication (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
[2022-05-31 16:40:18,247] DEBUG Using SASL mechanism 'OAUTHBEARER' provided by client (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
[2022-05-31 16:40:18,248] DEBUG Set SASL server state to AUTHENTICATE during authentication (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
[2022-05-31 16:40:18,266] DEBUG Authentication complete; session max lifetime from broker config=43200000 ms, credential expiration=Wed Jun 01 04:40:18 UTC 2022 (43199983 ms); session expiration = Wed Jun 01 04:40:18 UTC 2022 (43199983 ms), sending 43199983 ms to client (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
[2022-05-31 16:40:18,266] DEBUG Set SASL server state to COMPLETE during authentication (org.apache.kafka.common.security.authenticator.SaslServerAuthenticator)
[2022-05-31 16:40:18,266] DEBUG [SocketServer brokerId=1] Successfully authenticated with /10.0.0.103 (org.apache.kafka.common.network.Selector)
[2022-05-31 16:40:18,267] DEBUG [SocketServer brokerId=1] Connection with /10.0.0.103 disconnected (org.apache.kafka.common.network.Selector)
java.io.EOFException
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:97)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:447)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:397)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at kafka.network.Processor.poll(SocketServer.scala:923)
	at kafka.network.Processor.run(SocketServer.scala:826)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by sidyag** [comment]
Figured it out. It turns out that in our Java client, we have a custom implementation of the SASL client that expects a response from the server on successful authentication. We have customised the server as well to do this. I was trying to reuse the same server. However, the OAuth SASL client in librdkafka expects an empty response on successful authentication.

On changing the SASLServer implementation on the server to return `new byte[0]` on successful authentication, the same client code was successful.
