### ISSUE TITLE
No work with kafka 0.8.2

### ISSUE THREAD

**Issue by haosdent** [confluentinc/confluent-kafka-python#146]
Hi, I set `broker.version.fallback` to 0.8.2 in python consumer client but it still not work when connect to 0.8.2 server.

**Comment by edenhill** [comment]
Please provide more details:
 * What exactly is not working?
 * Do you have any logs from the client and broker?
 * What is your client configuration?

**Comment by haosdent** [comment]
Hi @edenhill thanks a lot for your super fast response. Not working means I use the latest confluent python client to connect kafka server (0.8.2). And it failed. I saw this message in the kafka server log

```
[2017-03-08 01:03:37,191] ERROR Closing socket for /10.65.16.25 because of error (kafka.network.Processor)
kafka.common.KafkaException: Wrong request type 16
        at kafka.api.RequestKeys$.deserializerForKey(RequestKeys.scala:64)
        at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
        at kafka.network.Processor.read(SocketServer.scala:450)
        at kafka.network.Processor.run(SocketServer.scala:340)
        at java.lang.Thread.run(Thread.java:745)
```

I use this configuration

```
c = Consumer({
	'bootstrap.servers': '10.10.17.57',
	'group.id': 'test-consumer',
	'broker.version.fallback': '0.8.2',
})
```

**Comment by haosdent** [comment]
I am not sure if it associated with https://github.com/edenhill/librdkafka/issues/637 which means confluent-kafka-python only support kafka >= 0.9 ?

**Comment by edenhill** [comment]
Are you sure that exception is from the confluent-kafka-python?
Request type 16 is ListGroups which is not currently implemented in this Python client.

**Comment by haosdent** [comment]
I am sure, this is why I doubt confluent-kafka don't support 0.8.2

**Comment by haosdent** [comment]
Another error message from kafka log.
```
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'topics': java.nio.BufferUnderflowException
        at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:66)
        at org.apache.kafka.common.requests.JoinGroupRequest.parse(JoinGroupRequest.java:85)
        at kafka.api.JoinGroupRequestAndHeader$.readFrom(JoinGroupRequestAndHeader.scala:29)
        at kafka.api.RequestKeys$$anonfun$12.apply(RequestKeys.scala:50)
        at kafka.api.RequestKeys$$anonfun$12.apply(RequestKeys.scala:50)
        at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
        at kafka.network.Processor.read(SocketServer.scala:450)
        at kafka.network.Processor.run(SocketServer.scala:340)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by edenhill** [comment]
Are you calling subscribe()? This requires a >=0.9 broker.
For 0.8.x you will need to make do with assign()

**Comment by mtrienis** [comment]
@edenhill do you have any documentation outlining that constraint? I run into a similar problem and it was hard to tell what was going on.

**Comment by haosdent** [comment]
many thx @edenhill you are best

cc @mtrienis 

```
from confluent_kafka import TopicPartition
tp = TopicPartition('topic', 0)
c.assign([tp])
```

this work for me lah

**Comment by zjyExcelsior** [comment]
@edenhill Why not adapt 0.8.x to subscribe?

**Comment by edenhill** [comment]
@zjyExcelsior subscribe() requires functionality that was added to broker 0.9.0.0

**Comment by zjyExcelsior** [comment]
@edenhill OK. And I think the docs for confluent_kafka_python is too few. Can u please add more? If a new pythoner to use it, he may be at a loss :)

**Comment by edenhill** [comment]
Thanks for your feedback, it is on our backlog to improve documentation.

**Comment by zjyExcelsior** [comment]
Thx, as soon as better.
