### ISSUE TITLE
Strange output to the console

### ISSUE THREAD

**Issue by pomponchik** [confluentinc/confluent-kafka-python#1478]
# Description

Hello!

I got a strange output when I was doing some tests through Pytest:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/_pytest/main.py", line 270, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/_pytest/main.py", line 324, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/_pytest/main.py", line 349, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/_pytest/runner.py", line 112, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/_pytest/runner.py", line 131, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/_pytest/runner.py", line 222, in call_and_report
INTERNALERROR>     report: TestReport = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 55, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/_pytest/skipping.py", line 265, in pytest_runtest_makereport
INTERNALERROR>     rep = outcome.get_result()
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/_pytest/runner.py", line 366, in pytest_runtest_makereport
INTERNALERROR>     return TestReport.from_item_and_call(item, call)
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/_pytest/reports.py", line 349, in from_item_and_call
INTERNALERROR>     longrepr = item.repr_failure(excinfo)
INTERNALERROR>   File "/Users/evblinov/Desktop/Projects/kafkalib/venv/lib/python3.10/site-packages/_pytest/python.py", line 1823, in repr_failure
INTERNALERROR>     return self._repr_failure_py(excinfo, style=style)
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/_pytest/nodes.py", line 484, in _repr_failure_py
INTERNALERROR>     return excinfo.getrepr(
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/_pytest/_code/code.py", line 669, in getrepr
INTERNALERROR>     return fmt.repr_excinfo(self)
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/_pytest/_code/code.py", line 944, in repr_excinfo
INTERNALERROR>     reprtraceback = self.repr_traceback(excinfo_)
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/_pytest/_code/code.py", line 871, in repr_traceback
INTERNALERROR>     reprentry = self.repr_traceback_entry(entry, einfo)
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/_pytest/_code/code.py", line 822, in repr_traceback_entry
INTERNALERROR>     s = self.get_source(source, line_index, excinfo, short=short)
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/_pytest/_code/code.py", line 760, in get_source
INTERNALERROR>     lines.extend(self.get_exconly(excinfo, indent=indent, markall=True))
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/_pytest/_code/code.py", line 772, in get_exconly
INTERNALERROR>     exlines = excinfo.exconly(tryshort=True).split("\n")
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/_pytest/_code/code.py", line 588, in exconly
INTERNALERROR>     lines = format_exception_only(self.type, self.value)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/traceback.py", line 155, in format_exception_only
INTERNALERROR>     te = TracebackException(type(value), value, None, compact=True)
INTERNALERROR>   File "/my_project_path/venv/lib/python3.10/site-packages/exceptiongroup/_formatting.py", line 173, in __init__
INTERNALERROR>     e.__context__.__traceback__,
INTERNALERROR> AttributeError: 'cimpl.KafkaError' object has no attribute '__traceback__'
```

# How to reproduce

I do not fully understand the reason why this conclusion arises. The fact is that all my tests pass successfully, I don't get errors. This is just the output in my console when I run the tests. Therefore, I could not accurately reproduce the code that causes this error without dragging half of my project here for demonstration.

The logic of the code that outputs this output looks something like this:

```python
from confluent_kafka import KafkaError


def test_error():
    try:
        raise KafkaError(KafkaError._MSG_TIMED_OUT)
    except KafkaError as e:
        if e.retriable():
            do_something()
```

But if you try to run exactly the same code, you probably won't see a similar output.

# Checklist

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): ('1.9.2', 17367552)
 - [ ] Python version: 3.10.7
 - [ ] Apache Kafka broker version: it's not important in this case
 - [ ] Client configuration: it's not important in this case
 - [ ] Operating system: MacOS 12.5
 - [ ] Provide client logs (with `'debug': '..'` as necessary): DEBUG
 - [ ] Provide broker log excerpts - no
 - [ ] Critical issue - no

**Comment by pranavrth** [comment]
I am not able to reproduce this. Can you share more code to reproduce the same?

Also, you have mentioned about python 3.11. We recently added 3.11 wheels. Can you check this with the latest version (v2.0.2) as well?

**Comment by Umptor** [comment]
I'm getting the same error as above but my test gets the status "Terminated" instead which causes my pipelines to fail.

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\_pytest\main.py", line 270, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\_pytest\main.py", line 324, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\pluggy\_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\_pytest\main.py", line 349, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\pluggy\_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\_pytest\runner.py", line 112, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\_pytest\runner.py", line 131, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\_pytest\runner.py", line 222, in call_and_report
INTERNALERROR>     report: TestReport = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\pluggy\_callers.py", line 55, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\_pytest\skipping.py", line 265, in pytest_runtest_makereport
INTERNALERROR>     rep = outcome.get_result()
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\pluggy\_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\_pytest\runner.py", line 366, in pytest_runtest_makereport
INTERNALERROR>     return TestReport.from_item_and_call(item, call)
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\_pytest\reports.py", line 349, in from_item_and_call
INTERNALERROR>     longrepr = item.repr_failure(excinfo)
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\_pytest\python.py", line 1823, in repr_failure
INTERNALERROR>     return self._repr_failure_py(excinfo, style=style)
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\_pytest\nodes.py", line 484, in _repr_failure_py
INTERNALERROR>     return excinfo.getrepr(
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\_pytest\_code\code.py", line 669, in getrepr
INTERNALERROR>     return fmt.repr_excinfo(self)
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\_pytest\_code\code.py", line 944, in repr_excinfo
INTERNALERROR>     reprtraceback = self.repr_traceback(excinfo_)
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\_pytest\_code\code.py", line 871, in repr_traceback
INTERNALERROR>     reprentry = self.repr_traceback_entry(entry, einfo)
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\_pytest\_code\code.py", line 822, in repr_traceback_entry
INTERNALERROR>     s = self.get_source(source, line_index, excinfo, short=short)
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\_pytest\_code\code.py", line 760, in get_source
INTERNALERROR>     lines.extend(self.get_exconly(excinfo, indent=indent, markall=True))
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\_pytest\_code\code.py", line 772, in get_exconly
INTERNALERROR>     exlines = excinfo.exconly(tryshort=True).split("\n")
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\_pytest\_code\code.py", line 588, in exconly
INTERNALERROR>     lines = format_exception_only(self.type, self.value)
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\traceback.py", line 140, in format_exception_only
INTERNALERROR>     return list(TracebackException(etype, value, None).format_exception_only())
INTERNALERROR>   File "C:\Users\MyUser\Miniconda3\envs\stuff\lib\site-packages\exceptiongroup\_formatting.py", line 182, in __init__
INTERNALERROR>     e.__context__.__traceback__,
INTERNALERROR> AttributeError: 'cimpl.KafkaError' object has no attribute '__traceback__'

============================ no tests ran in 0.20s ============================

Process finished with exit code 3
```

### How to reproduce
```python
from confluent_kafka import KafkaError


def stuff(producer, topic, msg, retries=0):
    while retries >= 0:
        try:
            producer.begin_transaction()
            producer.produce(topic, msg)
            producer.commit_transaction()
        except KafkaError as e:
            if e.retriable():
                retries += 1
                continue
            elif e.abortable():
                producer.abort_transaction()
```
```python
from unittest.mock import MagicMock
from confluent_kafka import KafkaError

from app.stuff import stuff


def test_stuff():
    mock_producer = MagicMock()
    mock_producer.begin_transaction = MagicMock()
    mock_producer.produce = MagicMock()
    mock_producer.commit_transaction = MagicMock()

    def commit_transaction_side_effect():
        raise KafkaError(49)

    mock_producer.commit_transaction.side_effect = commit_transaction_side_effect

    stuff(mock_producer, "topic", "msg")
```

Python 3.9.13
confluent_kafka.libversion(): 1.9.2, 17367807
confluent_kafka.version(): 1.9.2, 17367552
OS: Windows and CentOS
