### ISSUE TITLE
Problem with producer - missing attribute

### ISSUE THREAD

**Issue by exo0** [confluentinc/confluent-kafka-python#1486]
Description
===========
I have a problem with creating my own producer using confluent-kafka-python. 
When I'm trying to run the producer I'm getting an error that FileDescriptor has no attribute 'containing_type' 

**Details:**
Operating system: Windows 10 22H2

Python packages versions:
libprotoc 3.21.9
protobuf 4.21.12
google 3.0.0
confluent-kafka 1.9.2

The error which I'm getting:
```
Traceback (most recent call last):
  File "D:/Program Files/PyCharm/PyCharm Community Edition 2022.2.2/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\PyCharm\PyCharm Community Edition 2022.2.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\Projekty\PassiveHome.Endpoint\protobuf_producer.py", line 80, in <module>
    main()
  File "D:\Projekty\PassiveHome.Endpoint\protobuf_producer.py", line 37, in main
    protobuf_serializer = ProtobufSerializer(message_pb2,
  File "D:\Projekty\PassiveHome.Endpoint\venv\lib\site-packages\confluent_kafka\schema_registry\protobuf.py", line 291, in __init__
    self._msg_index = _create_msg_index(descriptor)
  File "D:\Projekty\PassiveHome.Endpoint\venv\lib\site-packages\confluent_kafka\schema_registry\protobuf.py", line 92, in _create_msg_index
    while current.containing_type is not None:
AttributeError: 'google._upb._message.FileDescriptor' object has no attribute 'containing_type'
```

How to reproduce
================

**How the .proto file looks**
```proto
syntax = "proto3";

import "google/protobuf/timestamp.proto";
package PassiveHome.Endpoint;

message Message {
  int32 Id = 1;
  int32 EndpointId = 2;
  repeated AnalyzerMessage AnalyzerMessages = 3;

  message AnalyzerMessage{
    int32 AnalyzerId = 1;
    repeated SensorData SensorList =2;

    message SensorData {
      uint32 SensorId =1;
      float SensorValue =2;
      uint32 SensorType =3;
      google.protobuf.Timestamp CreatedAt =4;
    }
  }
}
```
**Generated message_pb2.py**
```py
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x14PassiveHome.Endpoint\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe0\x02\n\x07Message\x12\n\n\x02Id\x18\x01 \x01(\x05\x12\x12\n\nEndpointId\x18\x02 \x01(\x05\x12G\n\x10\x41nalyzerMessages\x18\x03 \x03(\x0b\x32-.PassiveHome.Endpoint.Message.AnalyzerMessage\x1a\xeb\x01\n\x0f\x41nalyzerMessage\x12\x12\n\nAnalyzerId\x18\x01 \x01(\x05\x12L\n\nSensorList\x18\x02 \x03(\x0b\x32\x38.PassiveHome.Endpoint.Message.AnalyzerMessage.SensorData\x1av\n\nSensorData\x12\x10\n\x08SensorId\x18\x01 \x01(\r\x12\x13\n\x0bSensorValue\x18\x02 \x01(\x02\x12\x12\n\nSensorType\x18\x03 \x01(\r\x12-\n\tCreatedAt\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=73
  _MESSAGE._serialized_end=425
  _MESSAGE_ANALYZERMESSAGE._serialized_start=190
  _MESSAGE_ANALYZERMESSAGE._serialized_end=425
  _MESSAGE_ANALYZERMESSAGE_SENSORDATA._serialized_start=307
  _MESSAGE_ANALYZERMESSAGE_SENSORDATA._serialized_end=425
# @@protoc_insertion_point(module_scope)

```

**Producer code** 

```python
import argparse
from uuid import uuid4

from six.moves import input

# Protobuf generated class; resides at ./protobuf/user_pb2.py
import protogenerated.message_pb2 as message_pb2
from confluent_kafka import Producer
from confluent_kafka.serialization import StringSerializer, SerializationContext, MessageField
from confluent_kafka.schema_registry import SchemaRegistryClient
from confluent_kafka.schema_registry.protobuf import ProtobufSerializer


def delivery_report(err, msg):
    """
    Reports the failure or success of a message delivery.

    Args:
        err (KafkaError): The error that occurred on None on success.
        msg (Message): The message that was produced or failed.
    """

    if err is not None:
        print("Delivery failed for User record {}: {}".format(msg.key(), err))
        return
    print('User record {} successfully produced to {} [{}] at offset {}'.format(
        msg.key(), msg.topic(), msg.partition(), msg.offset()))


def main():
    topic = "testTopic"

    schema_registry_conf = {'url': "http://schemaregistry:8545"}
    schema_registry_client = SchemaRegistryClient(schema_registry_conf)

    string_serializer = StringSerializer('utf8')
    protobuf_serializer = ProtobufSerializer(message_pb2,
                                             schema_registry_client,
                                             {'use.deprecated.format': False})


    producer_conf = {'bootstrap.servers': "localhost:19092"}

    producer = Producer(producer_conf)

    print("Producing user records to topic {}. ^C to exit.".format(topic))
    while True:
        # Serve on_delivery callbacks from previous calls to produce()
        producer.poll(0.0)
        try:
            user_name = input("Enter name: ")
            user_favorite_number = int(input("Enter favorite number: "))
            user_favorite_color = input("Enter favorite color: ")

            message = message_pb2.Message()
            message.Id = 1
            message.EndpointId = 1
            analyzerMessages = message.AnalyzerMessages.add()
            analyzerMessages.AnalyzerId = 1
            sensorList = analyzerMessages.SensorList.add()
            sensorList.SensorId = 1
            sensorList.SensorValue = float(1)
            sensorList.SensorType = 1

            producer.produce(topic=topic, partition=0,
                             key=string_serializer(str(uuid4())),
                             value=protobuf_serializer(message, SerializationContext(topic, MessageField.VALUE)),
                             on_delivery=delivery_report)
        except (KeyboardInterrupt, EOFError):
            break
        except ValueError:
            print("Invalid input, discarding record...")
            continue

    print("\nFlushing records...")
    producer.flush()


if __name__ == '__main__':
    main()

```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [x] Client configuration: `{...}`
 - [x] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by pranavrth** [comment]
How are you generating the `message_pb2.py`? which `protoc` version are you using

**Comment by exo0** [comment]
I'm generating the message_pb2.py with this command:
```
protoc -I="D:/Projekty/pythonProducer/proto" --python_out="D:/Projekty/pythonProducer/protogenerated" D:/Projekty/pythonProducer/proto/message.proto
```
I'm using this version of protoc ``` libprotoc 3.21.9```

**Comment by pranavrth** [comment]
You are incorrectly using `ProtobufSerializer`. Use `protobuf_serializer = ProtobufSerializer(message_pb2.Message,` instead of `protobuf_serializer = ProtobufSerializer(message_pb2,` int the code.
