### ISSUE TITLE
SystemError: <built-in method error of cimpl.Message object at 0x...> returned a result with an error set

### ISSUE THREAD

**Issue by TvoroG** [confluentinc/confluent-kafka-python#150]
Hi!
This error happens when kafka is down and I'm trying to send messages to kafka.

I just have this little piece of information:
```
_TRANSPORT(-195): ssl://127.0.0.1:9989/bootstrap: Connect to ipv4#127.0.0.1:9989 failed: Connection refused
_ALL_BROKERS_DOWN(-187): 1/1 brokers are down
KafkaWorker-27942: error: <built-in method error of cimpl.Message object at 0x7fda974a75f8> returned a result with an error set
```

And code looks like this:
```python
class KafkaWorker(Process):
    def __init__(self, *args, **kwargs):
        ...
    def run(self):
        ...
           conf = {
               'bootstrap.servers': servers,
               'queue.buffering.max.messages': queue_size,
               'batch.num.messages': queue_size,
               'default.topic.config': {'message.timeout.ms': 15000},
               'security.protocol': 'ssl',
               'ssl.ca.location': ca_file,
               'ssl.certificate.location': cert_file,
               'ssl.key.location': key_file
               'error_cb': self.error_cb,
               'on_delivery': self.dr_msg_cb,
               # 'stats_cb': self.stats_cb,
           }
           p = Producer(**conf)

           while not self._stop_event.is_set() and not self._stop_me_event.is_set():
                try:
                    work_id, msgs, total_bytes = self._work_q.get(timeout=1)
                    self._logger.debug('%s: get work %s', self.whoami, work_id)
                except q.Empty:
                    continue

                if not msgs:
                    continue

                for m in msgs:
                    try:
                        ip.produce(self._topic, m)
                    except BufferError as e:
                        self._save_msg(m, e)
                    except KafkaException as e:
                        self._save_msg(m, e)
                        self._log_kafka_error(e.args[0])
                    except:
                        self._save_msgs(msgs)
                        self._workdone_q.put(work_id)
                        raise

                try:
                    p.flush()
                except Exception as e:
                    self._logger.info('error: %s', e)
                    self._save_msgs(msgs)
                    raise
                finally:
                    self._workdone_q.put(work_id)

    def dr_msg_cb(self, err, msg):
        if msg.error():  # <------ error happens here
            self._fail_writer.write(msg.value())
            self._log_kafka_error(msg.error())

        if err:
            self._log_kafka_error(err)

    def error_cb(self, err):
        self._log_kafka_error(err)
```

I know it is not enough to locate a problem, but maybe you have some ideas about this?

**Comment by edenhill** [comment]
Is this on Python 3.6?

**Comment by TvoroG** [comment]
python 3.5.3

**Comment by TvoroG** [comment]
confluent_kafka-0.9.4
librdkafka-v0.9.4

**Comment by TvoroG** [comment]
```
KafkaWorker-268: error: <built-in method error of cimpl.Message object at 0x7f2ed33104c0> returned a result with an error set
KafkaWorker-268 cannot produce or flush messages: Traceback (most recent call last):
  File "/app/logeater.py", line 157, in dr_msg_cb
    self._log_kafka_error(msg.error())
  File "/app/logeater.py", line 179, in _log_kafka_error
    self._logger.error('%s(%s): %s', err.name(), str(err.code()), err.str())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 3: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/logeater.py", line 144, in run
    p.flush()
  File "/app/logeater.py", line 155, in dr_msg_cb
    if msg.error():
SystemError: <built-in method error of cimpl.Message object at 0x7f2ed33104c0> returned a result with an error set
```

**Comment by TvoroG** [comment]
Minimal example:
```python
from confluent_kafka import Producer


def main():
    def dr_msg_cb(err, msg):
        msg.error()
        raise Exception()

    def error_cb(err):
        # or here
        # raise Exception()
        pass

    conf = {
        'bootstrap.servers': 'kafka:9092',
        'default.topic.config': {'message.timeout.ms': 1000},
        'error_cb': error_cb,
        'on_delivery': dr_msg_cb,
    }
    p = Producer(**conf)

    msgs = [b'msg' for _ in range(2)]

    for m in msgs:
        p.produce('test', m)
    p.flush()


if __name__ == '__main__':
    main()

```

**Comment by edenhill** [comment]
@TvoroG Why did you close the issue?

**Comment by TvoroG** [comment]
I'll reopen the issue if this is a bug

**Comment by TvoroG** [comment]
What is helped me to make it work is `delivery.report.only.error` in conf.

**Comment by edenhill** [comment]
This is a bug in confluent_kafka, it raises an exception (or the callback does) AND returns a none null value, this is not allowed and is actively enforced in Python >= 3.5

**Comment by edenhill** [comment]
Workaround: avoid raising exceptions from delivery report callbacks.

**Comment by edenhill** [comment]
Fixed on librdkafka master (honour yield() from delivery report callbacks)

**Comment by olejorgenb** [comment]
Sorry for the grave digging, but I'm seeing now and this was the only existing issue I could find for this message. 

`SystemError: <built-in method consume of cimpl.Consumer object at 0x7fe3858d8d60> returned NULL without setting an exception` 

Raised from the `consume` method.

This seems to happen when the process is terminated using an SIGTERM signal. We catch this signal and use `sys.exit(0)` in the signal handler to allow the process to terminate more gracefully.

The active frame at signal time was our `on_revoke` callback. (it doesn't do anything special, meaning it will let the SystemExit exception through.

In our case it's not harm - other than cluttering our error reports.
