### ISSUE TITLE
'Debug: all' not working with Consumer

### ISSUE THREAD

**Issue by meerkat-citronella** [confluentinc/confluent-kafka-python#1520]
Description
===========
I am new to kafka and confluent-kafka specifically, so bear with me. 

I am attempting to authenticate to a kafka topic using SASL_SSL and OAUTHBEARER. I know for a fact that I am able to fetch an access token and authenticate to the topic successfully, because I can do it with the `kafka-python` client (but I am switching to `confluent-kafka` because this package is much better-maintained).

I am unable to authenticate successfully (I think--i don't know for sure, because nothing is being logged). I have tried multiple things to adjust the log level to print some debug statements, but nothing works. 

Things I have tried: 
- setting `'log_level': 7` on the consumer config
- setting `'debug': 'all'` on the consumer config

Expected behavior: setting `'debug': 'all'` should provide maximal logging to `stdout`. 

How to reproduce
================
my `oauth_cb`:
```    
def token_provider_wrapper(config_str):
    token_provider = TokenProvider(
            private_key_aws_secret_name=private_key_path,
            cert_aws_secret_name=cert_path,
            adfs_config=json.dumps(adfs_config),
    )
    token_json = token_provider._token()
    token = token_json["access_token"]
    expires_in = token_json["expires_in"]
    return (token, time.time() + expires_in)
```
Again, I know for a fact that the `token_json` returned from the `_token()` method contains a valid token, as I have used it to authenticate using a different client.

my `Consumer` configuration: 
```    
logging.basicConfig(level=logging.DEBUG)
log = logging.getLogger(__name__)

conf = {
        'security.protocol': 'SASL_SSL',
        'sasl.mechanisms': 'OAUTHBEARER',
        'bootstrap.servers': ','.join(bootstrap_servers),
        'group.id': consumer_group_name,
        'sasl.oauthbearer.config': 'oauth_cb',
        'oauth_cb': token_provider_wrapper,
        'auto.offset.reset': 'earliest',
        'log_level': 7,
        'logger': log,
        'debug': 'all'
}
consumer = Consumer(conf)
consumer.subscribe(topics=[topic_name])

tp = TopicPartition(topic_name)
consumer.assign([tp])
assignment = consumer.assignment()
log.info('assignment:')
log.info(assignment)

offsets = consumer.get_watermark_offsets(tp, timeout=10)
log.info('offsets:')
log.info(offsets)
```

When I run this, I get the following logs:

```
I:\venv\platform-distribution\Scripts\python.exe I:\projects\AMIDEA\platform-distribution\src\amidea_platform_distribution\core\TEMP_confluent_kafka_distributor.py 
INFO:__main__:assignment:
INFO:__main__:[TopicPartition{topic=connect-service-feedback-source,partition=%I32d,offset=%s,error=%s}]
Traceback (most recent call last):
  File "I:\projects\AMIDEA\platform-distribution\src\amidea_platform_distribution\core\TEMP_confluent_kafka_distributor.py", line 119, in <module>
    consume()
  File "I:\projects\AMIDEA\platform-distribution\src\amidea_platform_distribution\core\TEMP_confluent_kafka_distributor.py", line 87, in consume
    offsets = consumer.get_watermark_offsets(tp, timeout=10)
cimpl.KafkaException: KafkaError{code=_ALL_BROKERS_DOWN,val=-187,str="Failed to get watermark offsets: Local: All broker connections are down"}

Process finished with exit code 1
```

I would have expected much more informative logging, something in line with this post: https://github.com/confluentinc/confluent-kafka-python/issues/1043 

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
    `confluent_kafka.version() = ('2.0.2', 33554944)`
    `confluent_kafka.libversion() = ('2.0.2', 33555199)`
 - [x] Apache Kafka broker version:
    broker version: 2.5.0
 - [x] Client configuration: `{...}`
 - [x] Operating system:
    windows server 2016 standard version 1607
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
    **unable to provide this, see above**
 - [ ] Provide broker log excerpts
    **unable to provide this, as I do not own the topic**
 - [x] Critical issue

**Comment by meerkat-citronella** [comment]
Disregard this--it seemed to be caused by the editor I am using (IntelliJ). When I ran it in a pytest, adding `--log-cli-level DEBUG`, it logged fine

**Comment by meerkat-citronella** [comment]
Disregard this--it seemed to be caused by the editor I am using (IntelliJ). When I ran it in a pytest, adding `--log-cli-level DEBUG`, it logged fine
