### ISSUE TITLE
Admin describe topic: ResourceType enum not found in future-map

### ISSUE THREAD

**Issue by WaxWell-Bison** [confluentinc/confluent-kafka-python#1643]
Description
===========

The following code:

```python
from confluent_kafka.admin import AdminClient, ConfigResource

topic = "test"

admin: AdminClient = AdminClient(config)
topic_config = ConfigResource(ConfigResource.Type.TOPIC, topic)
admin.describe_configs([topic_config])
```

Throw the following runtime error:

`Resource ConfigResource(ResourceType.TOPIC,test) not found in future-map {ConfigResource(ResourceType.TOPIC,test): <Future at 0x7fb6244c2c10 state=running>}`

It looks like the two ConfigResource enum are not the same and I guess the `__hash__` function return different values.

```python
fut = futmap.get(resource, None)
   if fut is None:
      raise RuntimeError("Resource {} not found in future-map: {}".format(resource, futmap))
```

The environment showing the error is difficult to debug and I have no clue why the enum from the futmap is different from the Future whereas they look the same. The comparaison on their `__class__` is False.

I'm not experiencing similar issue on environment where I'm not running httpd with mod_wsgi.

How to reproduce
================

You can reproduce this as a wsgi script running behind an Apache web server.

Python3.8-mod_wsgi
httpd 2.4.37
Flask 2.0.3
confluent-kafka 1.9.2

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by pranavrth** [comment]
Can you please send the full code? I want to understand what are you doing with the future returned by `admin.describe_configs([topic_config])` call.

For me, its working fine in the 2.2.0 version. Can you try with that version?

**Comment by WaxWell-Bison** [comment]
```python

_admin = None

def init_app(app):
    global _admin
    if _admin is None:
        config = app.config["KAFKA"]
        _admin = AdminClient(config)
    return _admin

def get_cluster_metadata():
    timeout = current_app.config["KAFKA"].get("message.timeout.ms", 60000) / 1000
    return _admin.list_topics(timeout=timeout)

def get_topic_config(topic):
    timeout = current_app.config["KAFKA"].get("message.timeout.ms", 60000) / 1000
    topic_config = ConfigResource(ConfigResource.Type.TOPIC, str(topic))
    done, _ = concurrent.futures.wait(_admin.describe_configs([topic_config], request_timeout=timeout).values())
    return list(done)[0].result()

@kafka_api.route("/alive", methods=["GET"])
def alive():
    response = {
        "available_brokers": [],
        "confluent_kafka_version": confluent_kafka.version(),
        "librdkafka_version": confluent_kafka.libversion()
    }
    try:
        cluster_metadata = admin.get_cluster_metadata()
        response["available_brokers"] = list(map(lambda p: f"{p.host}:{p.port}", cluster_metadata.brokers.values()))
        if app.config["TOPIC"] not in cluster_metadata.topics:
            response["msg"] = f"Configured topic {app.config['TOPIC']} not found"
            return jsonify(response), HTTPStatus.SERVICE_UNAVAILABLE
        topic_config = admin.get_topic_config(app.config["TOPIC"])
        min_insync_replicas = int(topic_config["min.insync.replicas"].value)
        if any(map(lambda partition: len(partition.isrs) < min_insync_replicas, cluster_metadata.topics[app.config["TOPIC"]].partitions.values())):
            response["msg"] = f"Missing insync replicas"
            return jsonify(response), HTTPStatus.SERVICE_UNAVAILABLE
        response["msg"] = "Ok"
        return jsonify(response), HTTPStatus.OK
    except KafkaException as e:
        status = HTTPStatus.SERVICE_UNAVAILABLE
        response["msg"] = str(e.args[0].str())
    except Exception as e:
        status = HTTPStatus.INTERNAL_SERVER_ERROR
        response["msg"] = str(e)
    return jsonify(response), status
```

The response I receive is the following:

```json
{
    "available_brokers": [
        "XXXXXXX:9092"
    ],
    "confluent_kafka_version": [
        "2.3.0",
        33751040
    ],
    "librdkafka_version": [
        "2.3.0",
        33751295
    ],
    "msg": "Resource ConfigResource(ResourceType.TOPIC,XXXXXXX) not found in future-map: {ConfigResource(ResourceType.TOPIC,XXXXXXX): <Future at 0x7f75bc451c90 state=running>}"
}
```

The traceback I'm able to get:

```traceback
==> XXXXXXXXXXXXXXXXXX <==
Traceback (most recent call last):
    File "/XXXXXXXX/app.py", line 33, in alive
        topic_config = admin.get_topic_config(app.config["TOPIC"])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/XXXXXXXX/admin.py", line 23, in get_topic_config
        return list(done)[0].result()
               ^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib64/python3.11/concurrent/futures/_base.py", line 449, in result
        return self.__get_result()
               ^^^^^^^^^^^^^^^^^^^
    File "/usr/lib64/python3.11/concurrent/futures/_base.py", line 401, in __get_result
        raise self._exception
    File "/XXXXXXXX/confluent_kafka/admin/__init__.py", line 159, in _make_resource_result
        raise RuntimeError("Resource {} not found in future-map: {}".format(resource, futmap))
RuntimeError: Resource ConfigResource(ResourceType.TOPIC,XXXXXXXX) not found in future-map: {ConfigResource(ResourceType.TOPIC,XXXXXXXX): <Future at 0x7fe7eae36210 state=running>}

```

**Comment by WaxWell-Bison** [comment]
According to https://modwsgi.readthedocs.io/en/master/user-guides/application-issues.html#python-simplified-gil-state-api

```ini
WSGIApplicationGroup %{GLOBAL}
```

Seems to have fixed my issue

**Comment by nhaq-confluent** [comment]
@WaxWell-Bison from your latest comment, could I mark this issue as closed?
