### ISSUE TITLE
Unable to install using `pip install confluent-kafka==2.2.0`

### ISSUE THREAD

**Issue by JackMidd-Amido** [confluentinc/confluent-kafka-python#1648]
Description
===========
I am unable to install using `pip install confluent-kafka==2.2.0` due to error `ValueError: path '/Users/prathi/work/confluent-kafka-python/LICENSE.txt' cannot be absolute`

Windows 10
Python 3.12.0
Pip 23.2.1

I hope this is the correct place to post such an issue. Another team member is having the same issue.

How to reproduce
================
In a terminal with elevated privileges, run `pip install confluent-kafka==2.2.0`

The follow error occurs:
```
Collecting confluent-kafka==2.1.1
  Downloading confluent-kafka-2.1.1.tar.gz (122 kB)
     ---------------------------------------- 122.4/122.4 kB 1.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      running egg_info
      writing src\confluent_kafka.egg-info\PKG-INFO
      writing dependency_links to src\confluent_kafka.egg-info\dependency_links.txt
      writing requirements to src\confluent_kafka.egg-info\requires.txt
      writing top-level names to src\confluent_kafka.egg-info\top_level.txt
      reading manifest file 'src\confluent_kafka.egg-info\SOURCES.txt'
      Traceback (most recent call last):
        File "C:\Users\[user]\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\[user]\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\[user]\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-s7znqa4e\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-s7znqa4e\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-s7znqa4e\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-s7znqa4e\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 75, in <module>
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-s7znqa4e\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-s7znqa4e\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-s7znqa4e\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-s7znqa4e\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-s7znqa4e\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-s7znqa4e\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-s7znqa4e\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 318, in run
          self.find_sources()
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-s7znqa4e\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 326, in find_sources
          mm.run()
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-s7znqa4e\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 548, in run
          self.add_defaults()
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-s7znqa4e\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 593, in add_defaults
          self.read_manifest()
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-s7znqa4e\overlay\Lib\site-packages\setuptools\command\sdist.py", line 214, in read_manifest
          self.filelist.append(line)
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-s7znqa4e\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 485, in append
          path = convert_path(item)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\[user]\AppData\Local\Temp\pip-build-env-s7znqa4e\overlay\Lib\site-packages\setuptools\_distutils\util.py", line 139, in convert_path
          raise ValueError("path '%s' cannot be absolute" % pathname)
      ValueError: path '/Users/prathi/work/confluent-kafka-python/LICENSE.txt' cannot be absolute
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system:
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by pranavrth** [comment]
We don't support Python 3.12 yet. 

I need to check why `/Users/prathi` is appearing.

**Comment by JackMidd-Amido** [comment]
My mistake! Thanks for the quick response.

I can confirm that I can install using Python 3.11.6.

**Comment by anton-bocharov-3shape** [comment]
same issue

**Comment by rafaelferrero** [comment]
Same issue here

Windows 10 Pro and Python 3.10.9 by pip install
