### ISSUE TITLE
httpx migration problems

### ISSUE THREAD

**Issue by xdgrulez** [confluentinc/confluent-kafka-python#1882]
Description
===========

Seems that the Python client with the latest update to 2.6.2 is broken...

All kinds of modules probably required for httpx are seemingly not listed in the dependencies of confluent_kafka and when you import confluent_kafka, you get all kinds of errors like this:

ModuleNotFoundError: No module named 'httpx'
ModuleNotFoundError: No module named 'cachetools'
ModuleNotFoundError: No module named 'google.type'

etc.

How to reproduce
================

>>> import confluent_kafka
>>> from confluent_kafka.schema_registry.avro import AvroDeserializer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/bla/venv/lib/python3.10/site-packages/confluent_kafka/schema_registry/__init__.py", line 20, in <module>
    from .schema_registry_client import (
  File "/tmp/bla/venv/lib/python3.10/site-packages/confluent_kafka/schema_registry/schema_registry_client.py", line 26, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'
>>> from confluent_kafka.schema_registry.json_schema import JSONDeserializer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/bla/venv/lib/python3.10/site-packages/confluent_kafka/schema_registry/__init__.py", line 20, in <module>
    from .schema_registry_client import (
  File "/tmp/bla/venv/lib/python3.10/site-packages/confluent_kafka/schema_registry/schema_registry_client.py", line 26, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'
>>> from confluent_kafka.schema_registry.protobuf import ProtobufDeserializer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/bla/venv/lib/python3.10/site-packages/confluent_kafka/schema_registry/__init__.py", line 20, in <module>
    from .schema_registry_client import (
  File "/tmp/bla/venv/lib/python3.10/site-packages/confluent_kafka/schema_registry/schema_registry_client.py", line 26, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'

...and if you install httpx, you get other missing dependencies...

I think these dependencies should be part of confluent_kafka and should not have to be installed manually by the user...

Checklist
=========
Please provide the following information:

 - [X] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 2.6.2
 - [ ] Apache Kafka broker version: doesn't matter here
 - [ ] Client configuration: doesn't matter here
 - [ ] Operating system: doesn't matter here
 - [X] Provide client logs: see above
 - [ ] Provide broker log excerpts: doesn't matter here
 - [X] Critical issue: I think so...

**Comment by Nemeczek** [comment]
It actually crashed our Databricks jobs... It definately should no be smuggled in as a minor version patch

**Comment by scholer** [comment]
@Nemeczek - crashed our Databricks jobs as well. We have previously not pinned patch versions to allow for security updates, but I guess going forward we will use bots to update package dependencies as needed.

**Comment by tribeiro** [comment]
We have a CI build that is failing the same way with version 2.8 of the library.

**Comment by emasab** [comment]
Thanks for filing this issue, I want to point out that while the extra/optional dependencies were [documented in 2.6.2](https://github.com/confluentinc/confluent-kafka-python/commit/4b4a0a48666ba88c19f459b49b8846504a7e7f35), they were available in current form since [1.4.1](https://github.com/confluentinc/confluent-kafka-python/commit/a4d8b1dc9e8cfad5d51337102763c7e6bf5aa1a4#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R79).

Optional dependencies are inevitable for SR and serialization features as we don't want all users have to install for example the `protobuf` dependencies if they're only using `avro`, and they must install the third party dependencies through this Python feature.
