### ISSUE TITLE
No module named cimpl

### ISSUE THREAD

**Issue by poshch** [confluentinc/confluent-kafka-python#302]
Description
===========

I built confluent kafka using an existing librdkafka on a Linux machine, but I get an error about 'cimpl' when I try to use the module:

librdkafka is 0.9.4

[root@mybox:/tmp/confluent-kafka-python-master] [22:10:39] $ equery list librdkafka
 * Searching for librdkafka ...
[I--] [??] dev-libs/librdkafka-0.9.4:0/1

[root@mybox:/tmp/confluent-kafka-python-master] [22:10:39] $ python
Python 2.7.10 (default, Jun 13 2016, 14:52:39)
[GCC 4.9.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from confluent_kafka import Producer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "confluent_kafka/__init__.py", line 2, in <module>
    from .cimpl import (Consumer,  # noqa
ImportError: No module named cimpl
>>> quit()

I set the library path to /usr/lib and ran ldconfig

**Comment by edenhill** [comment]
Python is sometimes confused when running from the confluent-kafka-python source directory, it tries to pick up the module from the current directory rather than the installed location.
I suggest using `python setup.py build` (or `pip install .`) and then running from outside the confluent-kafka-python directory, or using `python setup.py develop` which seems to fix it as well for some reason.

Also: virtualenvs are good.

**Comment by abigbigbird** [comment]
It was well for me when i use it in pyspark, when i run it on spark, the command is  
```
spark-submit --jars /usr/home/hadoop/spark-streaming-kafka-0-8-assembly_2.11-2.3.2.jar --py-files /usr/home/hadoop/sherlock/sherlock.zip /usr/home/hadoop/sherlock/sherlock/analyze/mysql_streaming.py
```
## There is a error:
```
Traceback (most recent call last):
  File "/usr/home/hadoop/spark-2.3.2-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 235, in dump
    return Pickler.dump(self, obj)
  File "/usr/lib64/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python2.7/pickle.py", line 562, in save_tuple
    save(element)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/home/hadoop/spark-2.3.2-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 378, in save_function
    self.save_function_tuple(obj)
  File "/usr/home/hadoop/spark-2.3.2-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 529, in save_function_tuple
    save(closure_values)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python2.7/pickle.py", line 600, in save_list
    self._batch_appends(iter(obj))
  File "/usr/lib64/python2.7/pickle.py", line 633, in _batch_appends
    save(x)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/home/hadoop/spark-2.3.2-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 378, in save_function
    self.save_function_tuple(obj)
  File "/usr/home/hadoop/spark-2.3.2-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 529, in save_function_tuple
    save(closure_values)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python2.7/pickle.py", line 600, in save_list
    self._batch_appends(iter(obj))
  File "/usr/lib64/python2.7/pickle.py", line 636, in _batch_appends
    save(tmp[0])
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/home/hadoop/spark-2.3.2-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 378, in save_function
    self.save_function_tuple(obj)
  File "/usr/home/hadoop/spark-2.3.2-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 529, in save_function_tuple
    save(closure_values)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python2.7/pickle.py", line 600, in save_list
    self._batch_appends(iter(obj))
  File "/usr/lib64/python2.7/pickle.py", line 636, in _batch_appends
    save(tmp[0])
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/home/hadoop/spark-2.3.2-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 372, in save_function
    self.save_function_tuple(obj)
  File "/usr/home/hadoop/spark-2.3.2-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 529, in save_function_tuple
    save(closure_values)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python2.7/pickle.py", line 600, in save_list
    self._batch_appends(iter(obj))
  File "/usr/lib64/python2.7/pickle.py", line 636, in _batch_appends
    save(tmp[0])
  File "/usr/lib64/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/home/hadoop/spark-2.3.2-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 780, in save_reduce
    save(cls)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/home/hadoop/spark-2.3.2-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 639, in save_global
    self.save_dynamic_class(obj)
  File "/usr/home/hadoop/spark-2.3.2-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 476, in save_dynamic_class
    save(clsdict)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib64/python2.7/pickle.py", line 681, in _batch_setitems
    save(v)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/home/hadoop/spark-2.3.2-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 718, in save_classmethod
    self.save_reduce(type(obj), (orig_func,), obj=obj)
  File "/usr/home/hadoop/spark-2.3.2-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 786, in save_reduce
    save(args)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python2.7/pickle.py", line 548, in save_tuple
    save(element)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/home/hadoop/spark-2.3.2-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 372, in save_function
    self.save_function_tuple(obj)
  File "/usr/home/hadoop/spark-2.3.2-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 525, in save_function_tuple
    save(f_globals)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib64/python2.7/pickle.py", line 681, in _batch_setitems
    save(v)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/home/hadoop/spark-2.3.2-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/cloudpickle.py", line 630, in save_global
    __import__(modname)
ImportError: No module named cimpl
```
