### ISSUE TITLE
Is there any way to gather producer metrics? 

### ISSUE THREAD

**Issue by neoeahit** [confluentinc/confluent-kafka-python#43]
I dont see stats_cb being exposed. Are there any plans/works to expose stats_cb so that we can consume metrics? Also possible to see a sample(types of metrics) of these metrics exposed?

**Comment by edenhill** [comment]
@hqin Can you provide a stats sample for our friend?

**Comment by mtrienis** [comment]
Do producer metrics exist yet?

**Comment by edenhill** [comment]
@mtrienis Register a stats callback, set statistics.interval.ms, and have a look [here](https://github.com/edenhill/librdkafka/wiki/Statistics) for a description of the format

**Comment by mtrienis** [comment]
Thanks @edenhill, do you mind clarifying what version the callback function is supported on?

This is the error I'm getting using v0.92 confluent-kafka-python and v0.91 librdkafka. 

```
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/src/tests/system/TestKafkaDataChannel.py", line 37, in test_pushData_succeeds_with_callback
    channel = KafkaTestUtils.getDataChannel("example")
  File "/data/src/tests/TestUtils.py", line 54, in getDataChannel
    channel = KafkaDataChannel(channelConfig, topic)
  File "/data/src/bddatachannel/KafkaDataChannel.py", line 32, in __init__
    self._makeProducer()
  File "/data/src/bddatachannel/KafkaDataChannel.py", line 126, in _makeProducer
    self._producer = confluent_kafka.Producer(producer_config)
KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="Property "stats_cb" must be set through dedicated .._set_..() function"}
```
Code
```
        def my_stats_callback(stats_json_str):
            import pdb; pdb.set_trace()

        producer_config = {'bootstrap.servers': ','.join(self._config['brokers']),
                           'queue.buffering.max.ms': 1,
                           'socket.blocking.max.ms': 1,
                           'statistics.interval.ms': 250,
                           'socket.timeout.ms': 300,
                           'metadata.request.timeout.ms': 250,
                           'message.send.max.retries': 2,
                           'stats_cb': my_stats_callback,
                           'default.topic.config': {'message.timeout.ms': 350,
                                                    'request.timeout.ms': 250}}
```

**Comment by edenhill** [comment]
You need to upgrade to confluent-kafka-python v0.9.4
