### ISSUE TITLE
No fallback to system CAs

### ISSUE THREAD

**Issue by swenzel** [confluentinc/confluent-kafka-python#527]
Description
===========
When using this package, librdkafka doesn't find our CA. Our brokers use GlobalSign CA which every client should have.
Any idea what's happening here?

How to reproduce
================
When I run:
```
kafkacat  -b broker01.our.domain:9092 -L -X security.protocol=SASL_SSL -X sasl.mechanisms=SCRAM-SHA-512 -X sasl.username=** -X sasl.password=**
```

it works fine but the equvalent python script:

```
from confluent_kafka.admin import AdminClient, ConfigResource
from confluent_kafka import Producer, Consumer, TopicPartition

config = {
    'bootstrap.servers': 'broker01.our.domain:9092',
    'security.protocol': 'SASL_SSL',
    'debug': 'all',
    'log_level': '0',
#    'ssl.ca.location': '/etc/ssl/certs/GlobalSign_Root_CA.pem',
    'sasl.mechanisms': 'SCRAM-SHA-512',
    'sasl.username': '**',
    'sasl.password': '**'
}

a = AdminClient(config)
print('\n'.join(a.list_topics().topics))
```

Only works if 'ssl.ca.location' is set.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version:
 - 1. Python
  Version: ('0.11.6', 722432)
  Libversion: ('0.11.6', 722687)
 - 2. Kafkacat
  Version 1.3.1 (JSON) (librdkafka 0.11.3 builtin.features=gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins)

 - [x] Apache Kafka broker version:
2.1.0

 - [x] Client configuration:
`{
    'bootstrap.servers': 'broker01.our.domain:9092',
    'security.protocol': 'SASL_SSL',
    'debug': 'all',
    'log_level': '0',
    'sasl.mechanisms': 'SCRAM-SHA-512',
    'sasl.username': '**',
    'sasl.password': '**'
}`
 - [x] Operating system:
```
➜  cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

➜  uname -a
Linux user-ThinkPad-T480 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```
 - [x] Provide client logs (with `'debug': '..'` as necessary):
```
%7|1548332520.683|SASL|rdkafka#producer-1| [thrd:app]: Selected provider SCRAM (builtin) for SASL mechanism SCRAM-SHA-512
%7|1548332520.684|OPENSSL|rdkafka#producer-1| [thrd:app]: librdkafka built with OpenSSL version 0x1000210f
%7|1548332520.685|BROKER|rdkafka#producer-1| [thrd:app]: sasl_ssl://broker01.our.domain:9092/bootstrap: Added new broker with NodeId -1
%7|1548332520.685|BROKER|rdkafka#producer-1| [thrd:app]: sasl_ssl://broker02.our.domain:9092/bootstrap: Added new broker with NodeId -1
%7|1548332520.685|BRKMAIN|rdkafka#producer-1| [thrd:sasl_ssl://broker01.our.domain:9092/bootstrap]: sasl_ssl://broker01.our.domain:9092/bootstrap: Enter main broker thread
%7|1548332520.685|BRKMAIN|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1548332520.685|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://broker01.our.domain:9092/bootstrap]: sasl_ssl://broker01.our.domain:9092/bootstrap: broker in state INIT connecting
%7|1548332520.685|STATE|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Broker changed state INIT -> UP
%7|1548332520.685|BROADCAST|rdkafka#producer-1| [thrd::0/internal]: Broadcasting state change
%7|1548332520.685|BROKER|rdkafka#producer-1| [thrd:app]: sasl_ssl://broker03.our.domain:9092/bootstrap: Added new broker with NodeId -1
%7|1548332520.685|INIT|rdkafka#producer-1| [thrd:app]: librdkafka v0.11.6 (0xb06ff) rdkafka#producer-1 initialized (builtin.features 0xffff, debug 0x203)
%7|1548332520.685|BRKMAIN|rdkafka#producer-1| [thrd:sasl_ssl://broker03.our.domain:9092/bootstrap]: sasl_ssl://broker03.our.domain:9092/bootstrap: Enter main broker thread
%7|1548332520.685|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://broker03.our.domain:9092/bootstrap]: sasl_ssl://broker03.our.domain:9092/bootstrap: broker in state INIT connecting
%7|1548332520.685|BRKMAIN|rdkafka#producer-1| [thrd:sasl_ssl://broker02.our.domain:9092/bootstrap]: sasl_ssl://broker02.our.domain:9092/bootstrap: Enter main broker thread
%7|1548332520.685|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://broker02.our.domain:9092/bootstrap]: sasl_ssl://broker02.our.domain:9092/bootstrap: broker in state INIT connecting
%7|1548332520.709|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://broker03.our.domain:9092/bootstrap]: sasl_ssl://broker03.our.domain:9092/bootstrap: Connecting to ipv4###.##.##.131:9092 (sasl_ssl) with socket 67
%7|1548332520.709|STATE|rdkafka#producer-1| [thrd:sasl_ssl://broker03.our.domain:9092/bootstrap]: sasl_ssl://broker03.our.domain:9092/bootstrap: Broker changed state INIT -> CONNECT
%7|1548332520.709|BROADCAST|rdkafka#producer-1| [thrd:sasl_ssl://broker03.our.domain:9092/bootstrap]: Broadcasting state change
%7|1548332520.710|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://broker02.our.domain:9092/bootstrap]: sasl_ssl://broker02.our.domain:9092/bootstrap: Connecting to ipv4###.##.##.5:9092 (sasl_ssl) with socket 66
%7|1548332520.710|STATE|rdkafka#producer-1| [thrd:sasl_ssl://broker02.our.domain:9092/bootstrap]: sasl_ssl://broker02.our.domain:9092/bootstrap: Broker changed state INIT -> CONNECT
%7|1548332520.710|BROADCAST|rdkafka#producer-1| [thrd:sasl_ssl://broker02.our.domain:9092/bootstrap]: Broadcasting state change
%7|1548332520.710|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://broker01.our.domain:9092/bootstrap]: sasl_ssl://broker01.our.domain:9092/bootstrap: Connecting to ipv4###.##.##.241:9092 (sasl_ssl) with socket 64
%7|1548332520.710|STATE|rdkafka#producer-1| [thrd:sasl_ssl://broker01.our.domain:9092/bootstrap]: sasl_ssl://broker01.our.domain:9092/bootstrap: Broker changed state INIT -> CONNECT
%7|1548332520.710|BROADCAST|rdkafka#producer-1| [thrd:sasl_ssl://broker01.our.domain:9092/bootstrap]: Broadcasting state change
%7|1548332520.718|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://broker01.our.domain:9092/bootstrap]: sasl_ssl://broker01.our.domain:9092/bootstrap: Connected to ipv4###.##.##.241:9092
%7|1548332520.718|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://broker02.our.domain:9092/bootstrap]: sasl_ssl://broker02.our.domain:9092/bootstrap: Connected to ipv4###.##.##.5:9092
%7|1548332520.718|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://broker03.our.domain:9092/bootstrap]: sasl_ssl://broker03.our.domain:9092/bootstrap: Connected to ipv4###.##.##.131:9092
%7|1548332520.750|BROKERFAIL|rdkafka#producer-1| [thrd:sasl_ssl://broker03.our.domain:9092/bootstrap]: sasl_ssl://broker03.our.domain:9092/bootstrap: failed: err: Local: SSL error: (errno: Success)
%7|1548332520.750|BROKERFAIL|rdkafka#producer-1| [thrd:sasl_ssl://broker01.our.domain:9092/bootstrap]: sasl_ssl://broker01.our.domain:9092/bootstrap: failed: err: Local: SSL error: (errno: Success)
%7|1548332520.750|BROKERFAIL|rdkafka#producer-1| [thrd:sasl_ssl://broker02.our.domain:9092/bootstrap]: sasl_ssl://broker02.our.domain:9092/bootstrap: failed: err: Local: SSL error: (errno: Success)
%3|1548332520.751|FAIL|rdkafka#producer-1| [thrd:sasl_ssl://broker02.our.domain:9092/bootstrap]: sasl_ssl://broker02.our.domain:9092/bootstrap: Failed to verify broker certificate: unable to get local issuer certificate (after 41ms in state CONNECT)
%3|1548332520.751|FAIL|rdkafka#producer-1| [thrd:sasl_ssl://broker01.our.domain:9092/bootstrap]: sasl_ssl://broker01.our.domain:9092/bootstrap: Failed to verify broker certificate: unable to get local issuer certificate (after 40ms in state CONNECT)
%3|1548332520.751|ERROR|rdkafka#producer-1| [thrd:sasl_ssl://broker01.our.domain:9092/bootstrap]: sasl_ssl://broker01.our.domain:9092/bootstrap: Failed to verify broker certificate: unable to get local issuer certificate (after 40ms in state CONNECT)
%3|1548332520.751|ERROR|rdkafka#producer-1| [thrd:sasl_ssl://broker02.our.domain:9092/bootstrap]: sasl_ssl://broker02.our.domain:9092/bootstrap: Failed to verify broker certificate: unable to get local issuer certificate (after 41ms in state CONNECT)
%3|1548332520.751|FAIL|rdkafka#producer-1| [thrd:sasl_ssl://broker03.our.domain:9092/bootstrap]: sasl_ssl://broker03.our.domain:9092/bootstrap: Failed to verify broker certificate: unable to get local issuer certificate (after 41ms in state CONNECT)
%3|1548332520.751|ERROR|rdkafka#producer-1| [thrd:sasl_ssl://broker03.our.domain:9092/bootstrap]: sasl_ssl://broker03.our.domain:9092/bootstrap: Failed to verify broker certificate: unable to get local issuer certificate (after 41ms in state CONNECT)
%7|1548332520.751|STATE|rdkafka#producer-1| [thrd:sasl_ssl://broker02.our.domain:9092/bootstrap]: sasl_ssl://broker02.our.domain:9092/bootstrap: Broker changed state CONNECT -> DOWN
%7|1548332520.751|BROADCAST|rdkafka#producer-1| [thrd:sasl_ssl://broker02.our.domain:9092/bootstrap]: Broadcasting state change
%7|1548332520.751|STATE|rdkafka#producer-1| [thrd:sasl_ssl://broker03.our.domain:9092/bootstrap]: sasl_ssl://broker03.our.domain:9092/bootstrap: Broker changed state CONNECT -> DOWN
%7|1548332520.751|STATE|rdkafka#producer-1| [thrd:sasl_ssl://broker01.our.domain:9092/bootstrap]: sasl_ssl://broker01.our.domain:9092/bootstrap: Broker changed state CONNECT -> DOWN
%7|1548332520.751|BROADCAST|rdkafka#producer-1| [thrd:sasl_ssl://broker03.our.domain:9092/bootstrap]: Broadcasting state change
%3|1548332520.751|ERROR|rdkafka#producer-1| [thrd:sasl_ssl://broker01.our.domain:9092/bootstrap]: 3/3 brokers are down
%7|1548332520.751|BROADCAST|rdkafka#producer-1| [thrd:sasl_ssl://broker01.our.domain:9092/bootstrap]: Broadcasting state change
%7|1548332521.750|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://broker02.our.domain:9092/bootstrap]: sasl_ssl://broker02.our.domain:9092/bootstrap: broker in state DOWN connecting
%7|1548332521.751|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://broker03.our.domain:9092/bootstrap]: sasl_ssl://broker03.our.domain:9092/bootstrap: broker in state DOWN connecting
%7|1548332521.751|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://broker01.our.domain:9092/bootstrap]: sasl_ssl://broker01.our.domain:9092/bootstrap: broker in state DOWN connecting
%7|1548332521.756|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://broker02.our.domain:9092/bootstrap]: sasl_ssl://broker02.our.domain:9092/bootstrap: Connecting to ipv4###.##.##.5:9092 (sasl_ssl) with socket 64
%7|1548332521.756|STATE|rdkafka#producer-1| [thrd:sasl_ssl://broker02.our.domain:9092/bootstrap]: sasl_ssl://broker02.our.domain:9092/bootstrap: Broker changed state DOWN -> CONNECT
%7|1548332521.756|BROADCAST|rdkafka#producer-1| [thrd:sasl_ssl://broker02.our.domain:9092/bootstrap]: Broadcasting state change
%7|1548332521.758|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://broker03.our.domain:9092/bootstrap]: sasl_ssl://broker03.our.domain:9092/bootstrap: Connecting to ipv4###.##.##.131:9092 (sasl_ssl) with socket 65
%7|1548332521.758|STATE|rdkafka#producer-1| [thrd:sasl_ssl://broker03.our.domain:9092/bootstrap]: sasl_ssl://broker03.our.domain:9092/bootstrap: Broker changed state DOWN -> CONNECT
%7|1548332521.758|BROADCAST|rdkafka#producer-1| [thrd:sasl_ssl://broker03.our.domain:9092/bootstrap]: Broadcasting state change
%7|1548332521.759|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://broker01.our.domain:9092/bootstrap]: sasl_ssl://broker01.our.domain:9092/bootstrap: Connecting to ipv4###.##.##.241:9092 (sasl_ssl) with socket 66
```
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Do you have the `ca-certificates` deb package installed?

**Comment by swenzel** [comment]
```
➜  sudo apt install ca-certificates
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ca-certificates is already the newest version (20180409).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by edenhill** [comment]
My guess is that the bundled openssl searches for certificates in some other location.
We'll look into it. Is this a standard Ubuntu 18.04 installation?

**Comment by swenzel** [comment]
Yes, it is. I can also try on a fresh VM if you want?

**Comment by edenhill** [comment]
Yes please, that'd be helpful

**Comment by swenzel** [comment]
Tested on fresh VMs with Ubuntu 14.04, 16.04 and 18.04
Behaviour on all machines is exactly the same as described before. Works with explicit CA but no fallback if CA is omitted.
Also for all distributions the certificates are at `/etc/ssl/certs` and I didn't have to install `ca-certificates` since they all had the latest version installed by default.

**Comment by edenhill** [comment]
This is hopefully fixed in the v1.0.0 release, please try it out.

**Comment by jaikiran** [comment]
@edenhill Although I'm not on Ubuntu, I have been running into similar issue on CentOS 7. We are using 1.1.0 of librdkafka:

```
librdkafka built with OpenSSL version 0x1000212f
librdkafka v1.1.0 (0x10100ff) rdkafka#producer-1 initialized (builtin.features gzip,snappy,ssl,sasl,regex,lz4,sasl_plain,sasl_scram,plugins,zstd,sasl_oauthbearer, GCC GXX PKGCONFIG INSTALL GNULD LDS LIBDL PLUGINS ZLIB SSL ZSTD HDRHISTOGRAM SNAPPY SOCKEM SASL_SCRAM SASL_OAUTHBEARER CRC32C_HW, debug 0x280)

```
On this system, the (default OS level) certs are at `/etc/ssl/certs` directory. When we _don't_ set `ssl.ca.location` property while constructing any of the librdkafka classes (for example `AdminClient`), then the SSL connection to the broker never happens. The client side (where this librdkafka library is used) keeps seeing errors like the following when the SSL handshake happens:
```
%7|1563447138.019|BROKERFAIL|rdkafka#producer-1| [thrd:ssl://ourhost:443/bootstrap]: ssl://ourhost:443/bootstrap: failed: err: Local: SSL error: (errno: Success)
```
On the Kafka broker side, we see the following error:
```
WRITE: TLSv1.2 Handshake, length = 3843
READ: TLSv1.2 Alert, length = 2
RECV TLSv1.2 ALERT:  fatal, unknown_ca
fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Received fatal alert: unknown_ca
fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Received fatal alert: unknown_ca
Connection with /xxx.yyy.zzz.client disconnected (org.apache.kafka.common.network.Selector)
javax.net.ssl.SSLException: Received fatal alert: unknown_ca
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1647)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1615)
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1781)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1070)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:896)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:766)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:479)
	at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:340)
	at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:265)
	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:170)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:547)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:483)
	at kafka.network.Processor.poll(SocketServer.scala:830)
	at kafka.network.Processor.run(SocketServer.scala:730)
	at java.lang.Thread.run(Thread.java:748)
```
This is a sign that during the SSL handshake, the broker sent a ServerHello (upon receiving the ClientHello from the client) to this librdkafka process which then rejected the handshake because of the cert presented by the broker not being something that this client trusts.
Looking at the code in `rdkafka_ssl.c` I see this code:
```
if (r == -1) {
                        /* Use default CA certificate paths: ignore failures */
                        r = SSL_CTX_set_default_verify_paths(ctx);
                        if (r != 1)
                                rd_kafka_dbg(
                                        rk, SECURITY, "SSL",
                                        "SSL_CTX_set_default_verify_paths() "
                                        "failed: ignoring");
                }
```
which gets invoked if no `ssl.ca.location` is set (our usecase). However, reading through the documentation of ```SSL_CTX_set_default_verify_paths``` here[1] it states:

> SSL_CTX_set_default_verify_paths() specifies that the default locations from which CA certificates are loaded should be used. There is one default directory and one default file. The default CA certificates directory is called "certs" in the default OpenSSL directory. Alternatively the SSL_CERT_DIR environment variable can be defined to override this location. The default CA certificates file is called "cert.pem" in the default OpenSSL directory. 

Clearly, the path on this OS `/etc/ssl/certs/` (and the files in that directory) doesn't match that expectation of OpenSSL. The same documentation further states that:
> Alternatively the SSL_CERT_FILE environment variable can be defined to override this location.

So, just to give it a try, I set this `SSL_CERT_FILE` environment variable, to point to `/etc/ssl/certs/ca-bundle.trust.crt` on my client side and invoked the same python client again and this time it connected and worked fine:
```
[thrd:ssl://ourhost:443/bootstrap]: ssl://ourhost:443/bootstrap: Broker SSL certificate verified
[thrd:ssl://ourhost:443/bootstrap]: ssl://ourhost:443/bootstrap: Connected (#1)
```
So it looks like the `SSL_CTX_set_default_verify_paths()` isn't enough to load the default paths on different OS.

I don't have a suggestion to make, on how to get this working without explicitly setting that environment variable. For us, in the product where we use librdkafka, we will have to evaluate what paths are valid paths for different flavours of OS to set this environment variable to the right paths. Do you think there's some other way to get the defaults loaded across platforms?

[1] https://www.openssl.org/docs/man1.1.0/man3/SSL_CTX_set_default_verify_paths.html

**Comment by edenhill** [comment]
Great analysis @jaikiran, and thanks for providing a workaround with `SSL_CERT_FILE`!

/etc/ssl/certs seems to be default location for both centos and debian, so it should be the default of the openssl we bundle with librdkafka and I thought this was the case already.
