### ISSUE TITLE
ImportError: cannot import name '_AdminClientImpl' ...

### ISSUE THREAD

**Issue by nmvega** [confluentinc/confluent-kafka-python#540]
Hello Friends:

I'm having the following issue intermittently:

```
(pyvenv.d) user@vps00$ ptpython
>>> rom confluent_kafka.admin import AdminClient, NewTopic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/agile.ds.d/stack.d/pyvenv.d/lib/python3.6/site-packages/confluent_kafka/admin/__init__.py", line 4, in <module>
    from ..cimpl import (KafkaException, # noqa
ImportError: cannot import name '_AdminClientImpl'
cannot import name '_AdminClientImpl'
```

I tried uninstalling/reinstalling the package as shown below, but the exception -- which disappeared the last time I did that -- isn't going away:
```
(pyvenv.d) user@vps00$ conda remove conda-forge python-confluent-kafka
(pyvenv.d) user@vps00$ conda install -c conda-forge python-confluent-kafka
[ ... snip ... ]

(pyvenv.d) user@vps00$ pip freeze | grep -i kafka
confluent-kafka==0.11.6
kafka-python==1.4.4
```

Any ideas? Thank you.

**Comment by nmvega** [comment]
An uninstall / reinstall of the package fixed my issue (but not necessarily a potential bug). Closing.
