### ISSUE TITLE
Python 3.6+ support?

### ISSUE THREAD

**Issue by fedenusy** [confluentinc/confluent-kafka-python#620]
Description
===========
This library requires `enum34`, [which is not compatible with Python 3.6+](https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag).

How to reproduce
================
Run a no-op `unittest` while requiring `confluent-kafka` and you should get something like:

```
Error in sitecustomize; set PYTHONVERBOSE for traceback:
AttributeError: module 'enum' has no attribute 'IntFlag'
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_fedenusy/82761fbb391b03a602abc1324ff91dda/sandbox/darwin-sandbox/55/execroot/com_github_softwaremotor_smc/bazel-out/darwin-fastbuild/bin/libpy/kafka/tests/test_consumer.runfiles/com_github_softwaremotor_smc/libpy/kafka/tests/test_consumer.py", line 1, in <module>
    import unittest
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/__init__.py", line 58, in <module>
    from .result import TestResult
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/result.py", line 5, in <module>
    import traceback
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/traceback.py", line 5, in <module>
    import linecache
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tokenize.py", line 33, in <module>
    import re
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/re.py", line 143, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
```

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 1.0.0
 - [ ] Apache Kafka broker version: n/a
 - [ ] Client configuration: `{...}` n/a
 - [ ] Operating system: macOS
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts: n/a
 - [ ] Critical issue

**Comment by edenhill** [comment]
This does not seem to be a problem with confluent-kafka-python, but with the enum34 package.
A quick search suggests the following solution: 
https://stackoverflow.com/a/45716067/1821055

**Comment by fedenusy** [comment]
Uninstalling enum34 triggers a different bug in confluent-kafka-python
