### ISSUE TITLE
Confluent kafka related error while executing python file in linkedin datahub quickstart guide

### ISSUE THREAD

**Issue by PriyaShaji** [confluentinc/confluent-kafka-python#774]
Description

===========
I am trying to execute linkedin datahub quickstart guide: [linkedin datahub](https://github.com/linkedin/datahub)
When I run the last command to ingest sample data `python mce_cli.py produce -d bootstrap_mce.dat`, it gives an error which I guess is related to confluent-kafka.

link to the mce-cli.py file: [mce-cli.py](https://github.com/linkedin/datahub/blob/master/metadata-ingestion/mce-cli/mce_cli.py)

link to quickstart docker-compose.yml file: [docker-compose.yml](https://github.com/linkedin/datahub/blob/master/docker/quickstart/docker-compose.yml)

-------------------

(NAME) t5ftsa06614:mce-cli pshaji$ python mce_cli.py produce -d bootstrap_mce.dat
Producing MetadataChangeEvent records to topic MetadataChangeEvent. ^c to exit.
Traceback (most recent call last):
File "mce_cli.py", line 108, in
main(parser.parse_args())
File "mce_cli.py", line 88, in main
produce(conf, args.data_file, args.schema_record)
File "mce_cli.py", line 32, in produce
producer.produce(topic=topic, value=content)
File "/Users/pshaji/.local/lib/python2.7/site-packages/confluent_kafka/avro/init.py", line 80, in produce
value = self._serializer.encode_record_with_schema(topic, value_schema, value)
File "/Users/pshaji/.local/lib/python2.7/site-packages/confluent_kafka/avro/serializer/message_serializer.py", line 105, in encode_record_with_schema
schema_id = self.registry_client.register(subject, schema)
File "/Users/pshaji/.local/lib/python2.7/site-packages/confluent_kafka/avro/cached_schema_registry_client.py", line 217, in register
result, code = self._send_request(url, method='POST', body=body)
File "/Users/pshaji/.local/lib/python2.7/site-packages/confluent_kafka/avro/cached_schema_registry_client.py", line 166, in _send_request
response = self._session.request(method, url, headers=_headers, json=body)
File "/Users/pshaji/.local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
resp = self.send(prep, **send_kwargs)
File "/Users/pshaji/.local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
r = adapter.send(request, **kwargs)
File "/Users/pshaji/.local/lib/python2.7/site-packages/requests/adapters.py", line 498, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))

---------------------------------------------------------------

How to reproduce

================

The environment I am working is:
Mac OS, 10.14.6
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

Unable to resolve this issue.

**Comment by rnpridgeon** [comment]
You need to add  a liveliness which ensures that the SR instance is up and ready to serve requests. It's not enough to start the image first.

An example might look like this. 

https://github.com/confluentinc/confluent-kafka-python/blob/master/tests/docker/bin/cluster_up.sh#L11-L27

**Comment by PriyaShaji** [comment]
Thank you @rnpridgeon for the reply. The issue is solved now. It was mainly a port issue and some bug fixes. You can refer [Linkedin datahub issues](https://github.com/linkedin/datahub/issues/1516 ) for reference.
