### ISSUE TITLE
No proper transformation for decimal type in confluent-kafka?

### ISSUE THREAD

**Issue by dimon777** [confluentinc/confluent-kafka-python#840]
Description
===========
I am following simple code for AvroConsumer to read from Debezium ingested Kafka topic and get this output in my avro consumer :

`{'before': None, 'after': {'rover_id': 1, 'he3_amount_kg': b'\x00\xa0', 'time': 1587854828723, 'lat': b'K\t', 'lon': b'\xdf\xa1i'}, 'source': {'version': '1.1.0.Final', 'connector': 'sqlserver', 'name': 'roversense-server', 'ts_ms': 1587854828723, 'snapshot': 'false', 'db': 'rover_sense', 'schema': 'dbo', 'table': 'rover_info', 'change_lsn': '00000028:00006900:0002', 'commit_lsn': '00000028:00006900:0003', 'event_serial_no': 1}, 'op': 'c', 'ts_ms': 1587854833111, 'transaction': None}`

Since schema registry is used and schema info is available for both: debezium producer and avro consumer, I would assume message should contain properly decoded Decimal fields instead of binary string: `b'\x00\xa0'`. Does current Avro implementation assume developer to write his own decoding to Decimal, or I miss some configuration item, or this feature is not implemented and in the roadmap?

How to reproduce
================
- Install confluent docker image 5.5.0-post as in https://docs.confluent.io/current/quickstart/ce-docker-quickstart.html
- Configure debezium SQL Server connector as in: https://docs.confluent.io/current/connect/debezium-connect-sqlserver/index.html
- Configure database and table with decimal field for CDC 
- Use kafka avro consumer as in https://github.com/confluentinc/confluent-kafka-python
- Observe above output.

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`): 5.5.0-post docker-compose image
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `{...}`
 - [ ] Operating system: Ubuntu 18.04
 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by bkkkk** [comment]
I'm having a similar issue. The data is serialized `BigDecimal` from Java/Scala and I'm having to decode it as a Decimal "by hand".

**Comment by rnpridgeon** [comment]
This is a limitation in the Apache Avro Python implementation. Try using FastAvro instead.

Alternatively you can use the new Generic Serde API which uses FastAvro exclusively. 

file:///Users/ryan/git_home/confluent/confluent-kafka-python/docs/_build/html/index.html#avrodeserializer

**Comment by bkkkk** [comment]
Just confirming that we moved to using the AvroDeserializer and this is no longer an issue.

**Comment by luancaarvalho** [comment]
Im trying too produce a Avro value with Decimal Type and getting this error:
```
Traceback (most recent call last):
  File "/home/luan/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/luan/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/luan/anaconda3/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/home/luan/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/luan/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/luan/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/luan/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/luan/anaconda3/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/home/luan/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/luan/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/luan/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/luan/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/luan/anaconda3/lib/python3.7/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/luan/anaconda3/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/luan/anaconda3/lib/python3.7/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/luan/fflask.py", line 18, in post
    return SendConfluentAvroToKafka(ID,topic)
  File "/home/luan/SendConfluentAvroToKafka.py", line 53, in SendConfluentAvroToKafka
    "fields": [
  File "/home/luan/anaconda3/lib/python3.7/site-packages/confluent_kafka/avro/load.py", line 31, in loads
    raise ClientError("Schema parse failed: %s" % (str(e)))
confluent_kafka.avro.error.ClientError: Schema parse failed: Error parsing schema from JSON: '\n  {\n    "type": "record",\n    "name": "Key",\n    "namespace": "customers.Key",\n    "fields": [\n      {\n        "name": "ID",\n      "type": {\n        "type": "bytes",\n        "logicalType": "decimal",\n        "precision": 38,\n        "scale": 0\n      }\n    ],\n    "connect.name": "customers.Key"\n  }\n  '. Error message: JSONDecodeError("Expecting ',' delimiter: line 15 column 5 (char 257)")
```

**Comment by ryananguiano** [comment]
I was able to decode using this using struct package.

https://avro.apache.org/docs/1.10.2/spec.html#Decimal
https://docs.python.org/3/library/struct.html#format-characters

```python
def decode_decimal(value: bytes, num_places: int) -> Decimal:
    value_size = len(value)
    for fmt in ('>B', '>H', '>L', '>Q'):
        if struct.calcsize(fmt) == value_size:
            int_value = struct.unpack(fmt, value)[0]
            scale = Decimal('1') / (10 ** num_places)
            return Decimal(int_value) * scale
```

**Comment by pranavrth** [comment]
Ryan solution is working for decimals. Closing this issue. Create a new one if you still face any issue.
