### ISSUE TITLE
TypeError: catching classes that do not inherit from BaseException is not allowed

### ISSUE THREAD

**Issue by slominskir** [confluentinc/confluent-kafka-python#849]
Description
===========
Occasionally I'll see the following stacktrace as my script closes connections to finish execution (automatically):

```
Exception ignored in: <bound method CachedSchemaRegistryClient.__del__ of <confluent_kafka.avro.cached_schema_registry_client.CachedSchemaRegistryClient object at 0x7f80990aed30>>
Traceback (most recent call last):
  File "/python/3.5.2/lib/confluent_kafka/avro/cached_schema_registry_client.py", line 120, in __del__
  File "/python/3.5.2/lib/confluent_kafka/avro/cached_schema_registry_client.py", line 129, in close
  File "/python/3.5.2/lib/requests/sessions.py", line 736, in close
  File "/python/3.5.2/lib/requests/adapters.py", line 325, in close
  File "/python/3.5.2/lib/urllib3/poolmanager.py", line 217, in clear
  File "/python/3.5.2/lib/urllib3/_collections.py", line 99, in clear
  File "/python/3.5.2/lib/urllib3/poolmanager.py", line 168, in <lambda>
  File "/python/3.5.2/lib/urllib3/connectionpool.py", line 475, in close
TypeError: catching classes that do not inherit from BaseException is not allowed
```

How to reproduce
================

Seems to be transient.   Maybe when I delete a schema via the REST interface from the registry and replace it with a new one from a Python script producer?  The script works fine, even with the error as the error occurs on connection close after my script has already done what I want.

Checklist
=========

$ pip3 show confluent-kafka
Name: confluent-kafka
Version: 1.4.0

$ pip3 show urllib3
Name: urllib3
Version: 1.25.9

$ cat /etc/redhat-release
Red Hat Enterprise Linux Workstation release 7.7 (Maipo)

**Comment by slominskir** [comment]
Looks like modifying the schema during development might be a contributing factor.   Perhaps the connectionpool.py class is caching something it shouldn't?   I noticed I spelled a word wrong in an enum type after producing a message, I changed two letters in the symbol that I had inverted and re-ran the producer script expecting to get a schema incompatible error, but instead the message went in fine, but I got a new exception on close:

```
Exception ignored in: <bound method CachedSchemaRegistryClient.__del__ of <confluent_kafka.avro.cached_schema_registry_client.CachedSchemaRegistryClient object at 0x7fb4d155dac8>>
Traceback (most recent call last):
  File "/python/3.5.2/lib/confluent_kafka/avro/cached_schema_registry_client.py", line 120, in __del__
  File "/python/3.5.2/lib/confluent_kafka/avro/cached_schema_registry_client.py", line 129, in close
  File "/python/3.5.2/lib/requests/sessions.py", line 736, in close
  File "/python/3.5.2/lib/requests/adapters.py", line 325, in close
  File "/python/3.5.2/lib/urllib3/poolmanager.py", line 217, in clear
  File "/python/3.5.2/lib/urllib3/_collections.py", line 99, in clear
  File "/python/3.5.2/lib/urllib3/poolmanager.py", line 168, in <lambda>
  File "/python/3.5.2/lib/urllib3/connectionpool.py", line 471, in close
  File "/python/3.5.2/lib/queue.py", line 175, in get
  File "/python/3.5.2/lib/threading.py", line 345, in notify
TypeError: 'NoneType' object is not callable
```

**Comment by slominskir** [comment]
Seems newer version of Python (3.7.6) does not have this issue.

**Comment by doctormohamed** [comment]
Hi @slominskir , I see you are using threading, I faced similar issue with multiprocess and solved it by closing the schema registry client: **registry_client.close()** last line of code
