### ISSUE TITLE
Undefined symbol: PyUnicodeUCS2_FromObject

### ISSUE THREAD

**Issue by BrennenSprimont** [confluentinc/confluent-kafka-python#915]
Description
===========

Python2.7 on Ubuntu18.04.03
confluent_kafka version: 1.4.2

When upgrading to 1.4.2 from (1.1.0), I get an undefined symbol in the "confluent_kafka/cimpl.so" file for PyUnicodeUCS2_FromObject.

Traceback:
```
Traceback (most recent call last):
  File "/azure_event_hub_to_kafka/azure_event_hub_to_kafka.py", line 17, in <module>
    import confluent_kafka
  File "/usr/local/lib/python2.7/dist-packages/confluent_kafka/__init__.py", line 19, in <module>
    from .deserializing_consumer import DeserializingConsumer
  File "/usr/local/lib/python2.7/dist-packages/confluent_kafka/deserializing_consumer.py", line 19, in <module>
    from confluent_kafka.cimpl import Consumer as _ConsumerImpl
ImportError: /usr/local/lib/python2.7/dist-packages/confluent_kafka/cimpl.so: undefined symbol: PyUnicodeUCS2_FromObject
```

confluent_kafka Version:
```
user@machine:/# pip show confluent_kafka
Name: confluent-kafka
Version: 1.4.2
Summary: Confluent's Python client for Apache Kafka
Home-page: https://github.com/confluentinc/confluent-kafka-python
Author: Confluent Inc
Author-email: support@confluent.io
License: UNKNOWN
Location: /usr/local/lib/python2.7/dist-packages
Requires: enum34, futures
```

OS Version:
```
user@machine:/# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

How to reproduce
================
Install the latest version of confluent_kafka from pip, then run "import confluent_kafka".

```
user@machine:/# pip install confluent_kafka
user@machine:/# python
Python 2.7.17 (default, Apr 15 2020, 17:20:14) 
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import confluent_kafka
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/confluent_kafka/__init__.py", line 19, in <module>
    from .deserializing_consumer import DeserializingConsumer
  File "/usr/local/lib/python2.7/dist-packages/confluent_kafka/deserializing_consumer.py", line 19, in <module>
    from confluent_kafka.cimpl import Consumer as _ConsumerImpl
ImportError: /usr/local/lib/python2.7/dist-packages/confluent_kafka/cimpl.so: undefined symbol: PyUnicodeUCS2_FromObject
```

Checklist
=========
Please provide the following information:

 - [1.4.2 ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
Can't provide. Can't open 
 - [Not relevant ] Apache Kafka broker version:
 - [Not relevant ] Client configuration: `{...}`
 - [Ubuntu18.04 ] Operating system:
 - [Not relevant  ] Provide client logs (with `'debug': '..'` as necessary)
 - [Not relevant  ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rnpridgeon** [comment]
Related to https://github.com/confluentinc/confluent-kafka-python/issues/882.

We will be updating our build tooling to py 3 so we can upgrade ci-buildwheel to a version which remedies this.

**Comment by edenhill** [comment]
Fixed
