### ISSUE TITLE
segfault with rdkafka 0.9.2 on mac

### ISSUE THREAD

**Issue by patrickviet** [confluentinc/confluent-kafka-python#92]
I obviously don't have 100+ MB messages on my kafka topic
Works perfectly with other consumers such as the java consumer.
kafka server is 0.10.1.0
the topic has 8 partitions and receives a few messages in blocks, every few seconds, nothing too crazy.

```% mytopic [0] end of queue, offset 48
%7|1480632843.583|DESP|rdkafka#consumer-1| Setting topic mytopic [0] partition as desired
%7|1480632843.583|DESP|rdkafka#consumer-1| Setting topic mytopic [0] partition as desired
%7|1480632843.583|DESP|rdkafka#consumer-1| Setting topic mytopic [0] partition as desired
%7|1480632843.583|DESP|rdkafka#consumer-1| Setting topic mytopic [0] partition as desired
%7|1480632843.583|DESP|rdkafka#consumer-1| Setting topic mytopic [0] partition as desired
%7|1480632843.583|DESP|rdkafka#consumer-1| Setting topic mytopic [0] partition as desired
%7|1480632843.583|DESP|rdkafka#consumer-1| Setting topic mytopic [0] partition as desired
%7|1480632843.583|DESP|rdkafka#consumer-1| Setting topic mytopic [0] partition as desired
%7|1480632843.583|DESP|rdkafka#consumer-1| Setting topic mytopic [0] partition as desired
%7|1480632843.583|DESP|rdkafka#consumer-1| Setting topic mytopic [0] partition as desired
%7|1480632843.583|DESP|rdkafka#consumer-1| Setting topic mytopic [0] partition as desired
%7|1480632843.583|DESP|rdkafka#consumer-1| Setting topic mytopic [0] partition as desired
%7|1480632843.583|DESP|rdkafka#consumer-1| Setting topic mytopic [0] partition as desired
%7|1480632843.583|DESP|rdkafka#consumer-1| Setting topic mytopic [0] partition as desired
%7|1480632843.583|DESP|rdkafka#consumer-1| Setting topic mytopic [0] partition as desired
%7|1480632843.583|DESP|rdkafka#consumer-1| Setting topic mytopic [0] partition as desired
%7|1480632843.583|DESP|rdkafka#consumer-1| Setting topic mytopic [0] partition as desired
%7|1480632843.583|DESP|rdkafka#consumer-1| Setting topic mytopic [0] partition as desired
%7|1480632843.583|DESP|rdkafka#consumer-1| Setting topic mytopic [0] partition as desired
%7|1480632843.584|DESP|rdkafka#consumer-1| Setting topic mytopic [0] partition as desired
%7|1480632843.584|DESP|rdkafka#consumer-1| Setting topic mytopic [0] partition as desired
%7|1480632843.584|DESP|rdkafka#consumer-1| Setting topic mytopic [0] partition as desired
%7|1480632843.584|DESP|rdkafka#consumer-1| Setting topic mytopic [0] partition as desired
%7|1480632843.584|DESP|rdkafka#consumer-1| Setting topic mytopic [0] partition as desired
%7|1480632843.584|DESP|rdkafka#consumer-1| Setting topic mytopic [0] partition as desired
%3|1480632873.180|FAIL|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632873.180|ERROR|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632873.180|ERROR|rdkafka#consumer-1| 1/1 brokers are down
%3|1480632873.365|FAIL|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632873.365|ERROR|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632874.107|FAIL|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632874.107|ERROR|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632874.107|ERROR|rdkafka#consumer-1| 1/1 brokers are down
%3|1480632874.735|FAIL|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632874.736|ERROR|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632875.189|FAIL|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632875.189|ERROR|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632875.189|ERROR|rdkafka#consumer-1| 1/1 brokers are down
%3|1480632875.781|FAIL|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632875.781|ERROR|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632876.400|FAIL|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632876.400|ERROR|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632876.400|ERROR|rdkafka#consumer-1| 1/1 brokers are down
%3|1480632876.823|FAIL|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632876.823|ERROR|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632877.197|FAIL|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632877.197|ERROR|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632877.197|ERROR|rdkafka#consumer-1| 1/1 brokers are down
%3|1480632877.828|FAIL|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632877.828|ERROR|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632878.123|FAIL|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632878.123|ERROR|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632878.123|ERROR|rdkafka#consumer-1| 1/1 brokers are down
%3|1480632878.810|FAIL|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632878.810|ERROR|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632879.419|FAIL|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632879.419|ERROR|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632879.419|ERROR|rdkafka#consumer-1| 1/1 brokers are down
%3|1480632879.608|FAIL|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632879.608|ERROR|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632879.940|FAIL|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632879.941|ERROR|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632879.941|ERROR|rdkafka#consumer-1| 1/1 brokers are down
 %3|1480632880.476|FAIL|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632880.476|ERROR|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
^R
%3|1480632880.965|FAIL|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632880.965|ERROR|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632880.965|ERROR|rdkafka#consumer-1| 1/1 brokers are down
%3|1480632881.605|FAIL|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632881.605|ERROR|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632882.203|FAIL|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632882.203|ERROR|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632882.203|ERROR|rdkafka#consumer-1| 1/1 brokers are down
%3|1480632882.856|FAIL|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632882.856|ERROR|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632883.366|FAIL|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632883.366|ERROR|rdkafka#consumer-1| kafkahost:9092/1: Receive failed: Invalid message size 117440690 (0..100000000): increase receive.message.max.bytes
%3|1480632883.366|ERROR|rdkafka#consumer-1| 1/1 brokers are down
Raising exception
Traceback (most recent call last):
  File "consumer.py", line 198, in <module>
    pri_and_sec_loop("mytopic" % msg_type, msg_type, 'primary')
  File "consumer.py", line 91, in pri_and_sec_loop
    raise KafkaException(msg.error())
cimpl.KafkaException: KafkaError{code=_BAD_MSG,val=-199,str="GroupCoordinator response error: Local: Bad message format"}
%7|1480632883.454|DESTROY|rdkafka#consumer-1| Terminating instance
%7|1480632883.543|PAUSE|rdkafka#consumer-1| Library pausing 8 partition(s)
%7|1480632883.543|BARRIER|rdkafka#consumer-1| mytopic [0]: rd_kafka_toppar_op_pause_resume:2020: new version barrier v3
%7|1480632883.543|PAUSE|rdkafka#consumer-1| Pause mytopic [0] (v3)
%7|1480632883.543|BARRIER|rdkafka#consumer-1| mytopic [1]: rd_kafka_toppar_op_pause_resume:2020: new version barrier v3
%7|1480632883.543|PAUSE|rdkafka#consumer-1| Pause mytopic [1] (v3)
%7|1480632883.543|BARRIER|rdkafka#consumer-1| mytopic [2]: rd_kafka_toppar_op_pause_resume:2020: new version barrier v3
%7|1480632883.543|PAUSE|rdkafka#consumer-1| Pause mytopic [2] (v3)
%7|1480632883.543|BARRIER|rdkafka#consumer-1| mytopic [3]: rd_kafka_toppar_op_pause_resume:2020: new version barrier v3
%7|1480632883.543|PAUSE|rdkafka#consumer-1| Pause mytopic [3] (v3)
%7|1480632883.543|BARRIER|rdkafka#consumer-1| mytopic [4]: rd_kafka_toppar_op_pause_resume:2020: new version barrier v3
%7|1480632883.543|PAUSE|rdkafka#consumer-1| Pause mytopic [4] (v3)
%7|1480632883.543|BARRIER|rdkafka#consumer-1| mytopic [5]: rd_kafka_toppar_op_pause_resume:2020: new version barrier v3
%7|1480632883.543|PAUSE|rdkafka#consumer-1| Pause mytopic [5] (v3)
%7|1480632883.543|BARRIER|rdkafka#consumer-1| mytopic [6]: rd_kafka_toppar_op_pause_resume:2020: new version barrier v3
%7|1480632883.543|PAUSE|rdkafka#consumer-1| Pause mytopic [6] (v3)
%7|1480632883.543|BARRIER|rdkafka#consumer-1| mytopic [7]: rd_kafka_toppar_op_pause_resume:2020: new version barrier v3
%7|1480632883.543|PAUSE|rdkafka#consumer-1| Pause mytopic [7] (v3)
%7|1480632883.543|OP|rdkafka#consumer-1| mytopic [0] received op PAUSE (v3) in fetch-state active (opv2)
%7|1480632883.543|PAUSE|rdkafka#consumer-1| Pause mytopic [0]: at offset 48 (state active, v3)
%7|1480632883.543|OP|rdkafka#consumer-1| mytopic [1] received op PAUSE (v3) in fetch-state active (opv2)
Segmentation fault: 11```

**Comment by edenhill** [comment]
What's your client config? With 0.10 brokers you should enable `"api.version.request": "true"` on the client.

Regarding the message sizes; multiple messages are typically batched together and these batches may grow big if the producer and consumer config is not synchronized, did you try increasing receive.message.max.bytes?

Regarding the GroupCoordinatorQuery: that's weird and really shouldn't happen. Is there anything useful in the broker logs?

Regarding the segfault: did it create a core file? If so, can you do:
```
  $ gdb python core
  gdb> bt
```
and provide the output.
Thanks

**Comment by edenhill** [comment]
ping @patrickviet

**Comment by edenhill** [comment]
Closed due to inactivity

**Comment by patrickviet** [comment]
I apologize for not giving further look.
And I do realize that this is free product yadda yadda yadda so nothing is owed to me.

I just can't be using in production a library that segfaults on invalid input, regardless of if I configured my kafka server incorrectly - it tells me that basic input checks are not being done.

Thanks and wish you the best
--Patrick
