### ISSUE TITLE
can't consume more than one topic partition and offset records messed up

### ISSUE THREAD

**Issue by patrickviet** [confluentinc/confluent-kafka-python#93]
I have a consumer. It's on a topic with 8 partitions, has a couple settings: 

```default.topic.config': {'auto.offset.reset':'earliest' }```
and
```'enable.auto.commit': False```

After having received and processed a message, I run an async commit with consumer.commit(message=msg)

It only seems to want to consume partition 0.
I don't understand.

A few logs

```
Starting primary loop
Connecting to Kafka with groupid mailfeedback5
assign: <cimpl.Consumer object at 0x1c99530> [TopicPartition{topic=mytopic,partition=0,offset=-1001,error=None}, TopicPartition{topic=mytopic,partition=1,offset=-1001,error=None}, TopicPartition{topic=mytopic,partition=2,offset=-1001,error=None}, TopicPartition{topic=mytopic,partition=3,offset=-1001,error=None}, TopicPartition{topic=mytopic,partition=4,offset=-1001,error=None}, TopicPartition{topic=mytopic,partition=5,offset=-1001,error=None}, TopicPartition{topic=mytopic,partition=6,offset=-1001,error=None}, TopicPartition{topic=mytopic,partition=7,offset=-1001,error=None}]
%7|1480633379.731|TOPIC|rdkafka#consumer-1| New local topic: mytopic
%7|1480633379.731|DESP|rdkafka#consumer-1| Adding desired topic mytopic [0]
%7|1480633379.731|DESP|rdkafka#consumer-1| Adding desired topic mytopic [1]
%7|1480633379.731|DESP|rdkafka#consumer-1| Adding desired topic mytopic [2]
%7|1480633379.731|DESP|rdkafka#consumer-1| Adding desired topic mytopic [3]
%7|1480633379.731|DESP|rdkafka#consumer-1| Adding desired topic mytopic [4]
%7|1480633379.731|DESP|rdkafka#consumer-1| Adding desired topic mytopic [5]
%7|1480633379.731|DESP|rdkafka#consumer-1| Adding desired topic mytopic [6]
%7|1480633379.731|DESP|rdkafka#consumer-1| Adding desired topic mytopic [7]
%7|1480633379.731|FETCHSTART|rdkafka#consumer-1| List with 8 partition(s):
%7|1480633379.731|FETCHSTART|rdkafka#consumer-1|  mytopic [0] offset INVALID
%7|1480633379.731|FETCHSTART|rdkafka#consumer-1|  mytopic [1] offset INVALID
%7|1480633379.731|FETCHSTART|rdkafka#consumer-1|  mytopic [2] offset INVALID
%7|1480633379.731|FETCHSTART|rdkafka#consumer-1|  mytopic [3] offset INVALID
%7|1480633379.731|FETCHSTART|rdkafka#consumer-1|  mytopic [4] offset INVALID
%7|1480633379.731|FETCHSTART|rdkafka#consumer-1|  mytopic [5] offset INVALID
%7|1480633379.731|FETCHSTART|rdkafka#consumer-1|  mytopic [6] offset INVALID
%7|1480633379.731|FETCHSTART|rdkafka#consumer-1|  mytopic [7] offset INVALID
%7|1480633379.731|OFFSET|rdkafka#consumer-1| kafkahost:9092/1: OffsetFetchRequest(v1) for 8/8 partition(s)
%7|1480633379.832|OFFSETFETCH|rdkafka#consumer-1| List with 8 partition(s):
%7|1480633379.832|OFFSETFETCH|rdkafka#consumer-1|  mytopic [0] offset INVALID
%7|1480633379.832|OFFSETFETCH|rdkafka#consumer-1|  mytopic [1] offset INVALID
%7|1480633379.832|OFFSETFETCH|rdkafka#consumer-1|  mytopic [2] offset INVALID
%7|1480633379.832|OFFSETFETCH|rdkafka#consumer-1|  mytopic [3] offset INVALID
%7|1480633379.832|OFFSETFETCH|rdkafka#consumer-1|  mytopic [4] offset INVALID
%7|1480633379.832|OFFSETFETCH|rdkafka#consumer-1|  mytopic [5] offset INVALID
%7|1480633379.832|OFFSETFETCH|rdkafka#consumer-1|  mytopic [6] offset INVALID
%7|1480633379.832|OFFSETFETCH|rdkafka#consumer-1|  mytopic [7] offset INVALID
%7|1480633379.832|OFFSET|rdkafka#consumer-1| Topic mytopic [0]: setting default offset INVALID
%7|1480633379.832|OFFSET|rdkafka#consumer-1| Topic mytopic [1]: setting default offset INVALID
%7|1480633379.832|OFFSET|rdkafka#consumer-1| Topic mytopic [2]: setting default offset INVALID
%7|1480633379.832|OFFSET|rdkafka#consumer-1| Topic mytopic [3]: setting default offset INVALID
%7|1480633379.832|OFFSET|rdkafka#consumer-1| Topic mytopic [4]: setting default offset INVALID
%7|1480633379.832|OFFSET|rdkafka#consumer-1| Topic mytopic [5]: setting default offset INVALID
%7|1480633379.832|OFFSET|rdkafka#consumer-1| Topic mytopic [6]: setting default offset INVALID
%7|1480633379.832|OFFSET|rdkafka#consumer-1| Topic mytopic [7]: setting default offset INVALID
%7|1480633379.832|OFFSETFETCH|rdkafka#consumer-1| kafkahost:9092/1: OffsetFetchResponse: mytopic [0] offset 51
%7|1480633379.832|OFFSETFETCH|rdkafka#consumer-1| kafkahost:9092/1: OffsetFetchResponse: mytopic [1] offset 1
%7|1480633379.832|OFFSETFETCH|rdkafka#consumer-1| kafkahost:9092/1: OffsetFetchResponse: mytopic [2] offset 2
%7|1480633379.832|OFFSETFETCH|rdkafka#consumer-1| kafkahost:9092/1: OffsetFetchResponse: mytopic [3] offset 2
%7|1480633379.832|OFFSETFETCH|rdkafka#consumer-1| kafkahost:9092/1: OffsetFetchResponse: mytopic [4] offset 2
%7|1480633379.832|OFFSETFETCH|rdkafka#consumer-1| kafkahost:9092/1: OffsetFetchResponse: mytopic [5] offset 2
%7|1480633379.832|OFFSETFETCH|rdkafka#consumer-1| kafkahost:9092/1: OffsetFetchResponse: mytopic [6] offset 2
%7|1480633379.832|OFFSETFETCH|rdkafka#consumer-1| kafkahost:9092/1: OffsetFetchResponse: mytopic [7] offset 2
%7|1480633379.832|OFFFETCH|rdkafka#consumer-1| kafkahost:9092/1: OffsetFetch for 8/8 partition(s) returned Success
%7|1480633379.832|FETCHSTART|rdkafka#consumer-1| List with 8 partition(s):
%7|1480633379.832|FETCHSTART|rdkafka#consumer-1|  mytopic [0] offset 51
%7|1480633379.832|FETCHSTART|rdkafka#consumer-1|  mytopic [1] offset 1
%7|1480633379.832|FETCHSTART|rdkafka#consumer-1|  mytopic [2] offset 2
%7|1480633379.832|FETCHSTART|rdkafka#consumer-1|  mytopic [3] offset 2
%7|1480633379.832|FETCHSTART|rdkafka#consumer-1|  mytopic [4] offset 2
%7|1480633379.832|FETCHSTART|rdkafka#consumer-1|  mytopic [5] offset 2
%7|1480633379.832|FETCHSTART|rdkafka#consumer-1|  mytopic [6] offset 2
%7|1480633379.832|FETCHSTART|rdkafka#consumer-1|  mytopic [7] offset 2
%7|1480633379.832|FETCH|rdkafka#consumer-1| Start fetch for mytopic [0] in state none at offset 51 (v2)
%7|1480633379.832|PARTSTATE|rdkafka#consumer-1| Partition mytopic [0] changed fetch state none -> active
%7|1480633379.832|FETCH|rdkafka#consumer-1| Start fetch for mytopic [1] in state none at offset 1 (v2)
%7|1480633379.832|PARTSTATE|rdkafka#consumer-1| Partition mytopic [1] changed fetch state none -> active
%7|1480633379.832|FETCH|rdkafka#consumer-1| Start fetch for mytopic [2] in state none at offset 2 (v2)
%7|1480633379.832|PARTSTATE|rdkafka#consumer-1| Partition mytopic [2] changed fetch state none -> active
%7|1480633379.832|FETCH|rdkafka#consumer-1| Start fetch for mytopic [3] in state none at offset 2 (v2)
%7|1480633379.832|PARTSTATE|rdkafka#consumer-1| Partition mytopic [3] changed fetch state none -> active
%7|1480633379.832|FETCH|rdkafka#consumer-1| Start fetch for mytopic [4] in state none at offset 2 (v2)
%7|1480633379.832|PARTSTATE|rdkafka#consumer-1| Partition mytopic [4] changed fetch state none -> active
%7|1480633379.832|FETCH|rdkafka#consumer-1| Start fetch for mytopic [5] in state none at offset 2 (v2)
%7|1480633379.832|PARTSTATE|rdkafka#consumer-1| Partition mytopic [5] changed fetch state none -> active
%7|1480633379.832|FETCH|rdkafka#consumer-1| Start fetch for mytopic [6] in state none at offset 2 (v2)
%7|1480633379.832|PARTSTATE|rdkafka#consumer-1| Partition mytopic [6] changed fetch state none -> active
%7|1480633379.832|FETCH|rdkafka#consumer-1| Start fetch for mytopic [7] in state none at offset 2 (v2)
%7|1480633379.832|PARTSTATE|rdkafka#consumer-1| Partition mytopic [7] changed fetch state none -> active
%7|1480633379.941|STATE|rdkafka#consumer-1| Topic mytopic changed state unknown -> exists
%7|1480633379.941|PARTCNT|rdkafka#consumer-1| Topic mytopic partition count changed from 0 to 8
%7|1480633379.941|BRKDELGT|rdkafka#consumer-1| Broker kafkahost:9092/1 is now leader for topic mytopic [2] with 0 messages (0 bytes) queued
%7|1480633379.941|BRKMIGR|rdkafka#consumer-1| Migrating topic mytopic [2] from (none) to kafkahost:9092/1
%7|1480633379.941|BRKDELGT|rdkafka#consumer-1| Broker kafkahost:9092/1 is now leader for topic mytopic [5] with 0 messages (0 bytes) queued
%7|1480633379.941|BRKMIGR|rdkafka#consumer-1| Migrating topic mytopic [5] from (none) to kafkahost:9092/1
%7|1480633379.941|BRKDELGT|rdkafka#consumer-1| Broker kafkahost:9092/1 is now leader for topic mytopic [4] with 0 messages (0 bytes) queued
%7|1480633379.941|BRKMIGR|rdkafka#consumer-1| Migrating topic mytopic [4] from (none) to kafkahost:9092/1
%7|1480633379.941|BRKDELGT|rdkafka#consumer-1| Broker kafkahost:9092/1 is now leader for topic mytopic [7] with 0 messages (0 bytes) queued
%7|1480633379.941|BRKMIGR|rdkafka#consumer-1| Migrating topic mytopic [7] from (none) to kafkahost:9092/1
%7|1480633379.941|BRKDELGT|rdkafka#consumer-1| Broker kafkahost:9092/1 is now leader for topic mytopic [1] with 0 messages (0 bytes) queued
%7|1480633379.941|BRKMIGR|rdkafka#consumer-1| Migrating topic mytopic [1] from (none) to kafkahost:9092/1
%7|1480633379.941|BRKDELGT|rdkafka#consumer-1| Broker kafkahost:9092/1 is now leader for topic mytopic [3] with 0 messages (0 bytes) queued
%7|1480633379.941|BRKMIGR|rdkafka#consumer-1| Migrating topic mytopic [3] from (none) to kafkahost:9092/1
%7|1480633379.941|BRKDELGT|rdkafka#consumer-1| Broker kafkahost:9092/1 is now leader for topic mytopic [6] with 0 messages (0 bytes) queued
%7|1480633379.941|BRKMIGR|rdkafka#consumer-1| Migrating topic mytopic [6] from (none) to kafkahost:9092/1
%7|1480633379.941|BRKDELGT|rdkafka#consumer-1| Broker kafkahost:9092/1 is now leader for topic mytopic [0] with 0 messages (0 bytes) queued
%7|1480633379.941|BRKMIGR|rdkafka#consumer-1| Migrating topic mytopic [0] from (none) to kafkahost:9092/1
%7|1480633379.941|METADATA|rdkafka#consumer-1| kafkahost:9092/1: Requested topic mytopic seen in metadata
%7|1480633380.042|TOPBRK|rdkafka#consumer-1| kafkahost:9092/1: Topic mytopic [2]: joining broker
%7|1480633380.042|TOPBRK|rdkafka#consumer-1| kafkahost:9092/1: Topic mytopic [5]: joining broker
%7|1480633380.042|TOPBRK|rdkafka#consumer-1| kafkahost:9092/1: Topic mytopic [4]: joining broker
%7|1480633380.042|TOPBRK|rdkafka#consumer-1| kafkahost:9092/1: Topic mytopic [7]: joining broker
%7|1480633380.042|TOPBRK|rdkafka#consumer-1| kafkahost:9092/1: Topic mytopic [1]: joining broker
%7|1480633380.042|TOPBRK|rdkafka#consumer-1| kafkahost:9092/1: Topic mytopic [3]: joining broker
%7|1480633380.042|TOPBRK|rdkafka#consumer-1| kafkahost:9092/1: Topic mytopic [6]: joining broker
%7|1480633380.042|TOPBRK|rdkafka#consumer-1| kafkahost:9092/1: Topic mytopic [0]: joining broker
%7|1480633380.142|FETCHDEC|rdkafka#consumer-1| Topic mytopic [2]: fetch decide: updating to version 2 (was 0) at offset 2 (was 0)
%7|1480633380.142|FETCHADD|rdkafka#consumer-1| kafkahost:9092/1: Added mytopic [2] to fetch list (1 entries, opv 2)
%7|1480633380.142|FETCHDEC|rdkafka#consumer-1| Topic mytopic [5]: fetch decide: updating to version 2 (was 0) at offset 2 (was 0)
%7|1480633380.142|FETCHADD|rdkafka#consumer-1| kafkahost:9092/1: Added mytopic [5] to fetch list (2 entries, opv 2)
%7|1480633380.142|FETCHDEC|rdkafka#consumer-1| Topic mytopic [4]: fetch decide: updating to version 2 (was 0) at offset 2 (was 0)
%7|1480633380.142|FETCHADD|rdkafka#consumer-1| kafkahost:9092/1: Added mytopic [4] to fetch list (3 entries, opv 2)
%7|1480633380.142|FETCHDEC|rdkafka#consumer-1| Topic mytopic [7]: fetch decide: updating to version 2 (was 0) at offset 2 (was 0)
%7|1480633380.142|FETCHADD|rdkafka#consumer-1| kafkahost:9092/1: Added mytopic [7] to fetch list (4 entries, opv 2)
%7|1480633380.142|FETCHDEC|rdkafka#consumer-1| Topic mytopic [1]: fetch decide: updating to version 2 (was 0) at offset 1 (was 0)
%7|1480633380.142|FETCHADD|rdkafka#consumer-1| kafkahost:9092/1: Added mytopic [1] to fetch list (5 entries, opv 2)
%7|1480633380.142|FETCHDEC|rdkafka#consumer-1| Topic mytopic [3]: fetch decide: updating to version 2 (was 0) at offset 2 (was 0)
%7|1480633380.142|FETCHADD|rdkafka#consumer-1| kafkahost:9092/1: Added mytopic [3] to fetch list (6 entries, opv 2)
%7|1480633380.142|FETCHDEC|rdkafka#consumer-1| Topic mytopic [6]: fetch decide: updating to version 2 (was 0) at offset 2 (was 0)
%7|1480633380.142|FETCHADD|rdkafka#consumer-1| kafkahost:9092/1: Added mytopic [6] to fetch list (7 entries, opv 2)
%7|1480633380.142|FETCHDEC|rdkafka#consumer-1| Topic mytopic [0]: fetch decide: updating to version 2 (was 0) at offset 51 (was 0)
%7|1480633380.142|FETCHADD|rdkafka#consumer-1| kafkahost:9092/1: Added mytopic [0] to fetch list (8 entries, opv 2)
% mytopic [0] end of queue, offset 51
^CTraceback (most recent call last):
  File "consumer.py", line 198, in <module>
    pri_and_sec_loop("mytopic", msg_type, 'primary')
  File "consumer.py", line 82, in pri_and_sec_loop
    msg = c.poll(timeout=1.0)
KeyboardInterrupt
%7|1480633385.205|DESTROY|rdkafka#consumer-1| Terminating instance
^C
```

**Comment by edenhill** [comment]
By the looks of your log it seems that you have committed offsets (on the broker) for all those partitions (the first partition's committed offset is at 51, the rest are at 1 or 2), so the client will start consuming at the stored offset + 1 for each partition.
If there has been no new messages produced since then the consumer will just sit and wait for new messages to be produced to those partitions.

Do you know if there are more messages than in those partitions, or if new messages are being produced?

**Comment by patrickviet** [comment]
Yes - there are other messages with offsets over 500 on all the other partitions, and message are being produced. The earlier ones expired though (offsets 1-400).
It seems the that the problem is if the offsets are wrong, the consumer can't repair the problem by skipping forward until the point where there are offsets

**Comment by edenhill** [comment]
Could it be that the lower offsets now represent deleted messages (due to topic retention time) and when the consumer tries to consume those offsets it will get an error back and retort to `auto.offset.reset` which defaults to `latest`.
If there are no new messages being produced to those partitions then the consumer will not see any messages for those partitions.

Does this seem like a reasonable explanation of what you are seeing?

**Comment by edenhill** [comment]
Closing due to inactivity
