### ISSUE TITLE
Avro Desrialization Error when Schema is primitive type.

### ISSUE THREAD

**Issue by lethrez** [confluentinc/confluent-kafka-python#989]
Description
===========

When attempting to use AvroDeserializer with a schema that is a primitive type for example "string" a value deserialization message is received.

Versions:
```
>>> confluent_kafka.version()
('1.5.0', 17104896)
>>> confluent_kafka.libversion()
('1.5.0', 17105151)
```
Confluent Platform: 6.0.0
MacOS

How to reproduce
================
Here is the producer code
``` python
from confluent_kafka.schema_registry import SchemaRegistryClient
from confluent_kafka.schema_registry.avro import AvroSerializer
from confluent_kafka.serializing_producer import SerializingProducer


def delivery_report(err, msg):
    if err is not None:
        print("Delivery failed for User record {}: {}".format(msg.key(), err))
        return
    print(
        "User record {} successfully produced to {} [{}] at offset {}".format(
            msg.key(), msg.topic(), msg.partition(), msg.offset()
        )
    )


# The AVRO Schema
schema_str = '{"type": "string"}'
value = "test"
# Schema Registry Client Initiliazation
schema_registry_configuration = {"url": "http://127.0.0.1:8081"}
schema_registry_client = SchemaRegistryClient(schema_registry_configuration)
# Producer Client Initiliazation
avro_serializer_configutation = {"auto.register.schemas": True}
producer_client_configuration = {
    "bootstrap.servers": "localhost:9092",
    "value.serializer": AvroSerializer(
        schema_str=schema_str, schema_registry_client=schema_registry_client, conf=avro_serializer_configutation
    ),
}
producer = SerializingProducer(producer_client_configuration)
# Produce a record with appropriate headers
producer.produce(topic="test", value=value, on_delivery=delivery_report)
# Flush producer
producer.flush()

```

Here is the consumer code:
```python
from confluent_kafka.schema_registry import SchemaRegistryClient
from confluent_kafka.schema_registry.avro import AvroDeserializer
from confluent_kafka.deserializing_consumer import DeserializingConsumer

# The AVRO Schema
schema_str = '{"type": "string"}'

schema_registry_configuration = {
    "url": "http://localhost:8081",
}
schema_registry_client = SchemaRegistryClient(schema_registry_configuration)
serializer = AvroDeserializer(schema_str=schema_str, schema_registry_client=schema_registry_client)
conf = {
    "client.id": "test_3",
    "bootstrap.servers": "localhost:9092",
    "auto.offset.reset": "earliest",
    "value.deserializer": serializer,  # Serializer used for message values.
    "group.id": "test-group",
}
consumer = DeserializingConsumer(conf)
try:
    consumer.subscribe(["test"])
    while True:
        message = consumer.poll(timeout=5.0)
        # id created to track logic through logs
        if message is None:
            continue
        else:
            print(message.value())
        consumer.commit(asynchronous=True)
except Exception as e:
    raise (e)
    print(e)

```

Running 
`python3 producer.py`
Then:
`python3 consumer.py`
We retrieve the following error from the consumer

```
Traceback (most recent call last):
  File "/Users/.../.pyenv/versions/3.8.1/lib/python3.8/site-packages/confluent_kafka/deserializing_consumer.py", line 137, in poll
    value = self._value_deserializer(value, ctx)
  File "/Users/.../.pyenv/versions/3.8.1/lib/python3.8/site-packages/confluent_kafka/schema_registry/avro.py", line 317, in __call__
    writer_schema = parse_schema(loads(
  File "/Users/.../.pyenv/versions/3.8.1/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Users/.../.pyenv/versions/3.8.1/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/.../.pyenv/versions/3.8.1/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 11 (char 10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "consumer.py", line 56, in <module>
    raise (e)
  File "consumer.py", line 39, in <module>
    message = consumer.poll(timeout=5.0)
  File "/Users/.../.pyenv/versions/3.8.1/lib/python3.8/site-packages/confluent_kafka/deserializing_consumer.py", line 139, in poll
    raise ValueDeserializationError(exception=se, kafka_message=msg)
confluent_kafka.error.ValueDeserializationError: KafkaError{code=_VALUE_DESERIALIZATION,val=-159,str="Expecting ',' delimiter: line 1 column 11 (char 10)"}
```
Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [x] Apache Kafka broker version:
 - [x] Client configuration: `{...}`
 - [x] Operating system:
 - [x] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by dylrich** [comment]
We have this same issue with version 1.5.0 and are monkey patching _schema_loads like this to fix the problem:

```python
    # canonical form primitive declarations are not supported
    if schema_str[0] != "{":
        schema_str = '{"type":' + schema_str + "}"
```

instead of:
https://github.com/confluentinc/confluent-kafka-python/blob/master/src/confluent_kafka/schema_registry/avro.py#L64-L66

**Comment by heidi-verica** [comment]
There is a similar issue in the the JSON deserializer implementation where json.loads() is called with encoding="utf8". However, the encoding keyword arg was removed in python 3.9.

Relevant code: https://github.com/confluentinc/confluent-kafka-python/blob/master/src/confluent_kafka/schema_registry/json_schema.py#L276

**Comment by msinto93** [comment]
We are seeing this same issue when trying to serialize using a primitive type avro schema. This looks like a bug in [_schema_loads](https://github.com/confluentinc/confluent-kafka-python/blob/master/src/confluent_kafka/schema_registry/avro.py#L64-L66)  which the PR linked above will fix, so could we get the PR approved and merged please?
